#!/usr/bin/env bash
set -ex;

echo "format tape as number '$1', name '$2'"
echo "copy '$3' to tape"

stenc -f /dev/st0 -e on -k /root/tape.key -a 1 --ckod
sleep 3
mkltfs -f -d /dev/st0 -s $1 -n $2
sleep 3
ltfs -o noatime -o sync_type=unmount -o work_directory=/opt/ltfs -o capture_index -o min_pool_size=256 -o max_pool_size=1024 -o eject /ltfs
sleep 3
ordercp $3 /ltfs/
sleep 3
umount /ltfs
