// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.0
// source: file_operation.proto

package entity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FileOperationService_Execute_FullMethodName = "/file_operation.FileOperationService/Execute"
)

// FileOperationServiceClient is the client API for FileOperationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileOperationServiceClient interface {
	Execute(ctx context.Context, in *ExecuteFileOperationRequest, opts ...grpc.CallOption) (FileOperationService_ExecuteClient, error)
}

type fileOperationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileOperationServiceClient(cc grpc.ClientConnInterface) FileOperationServiceClient {
	return &fileOperationServiceClient{cc}
}

func (c *fileOperationServiceClient) Execute(ctx context.Context, in *ExecuteFileOperationRequest, opts ...grpc.CallOption) (FileOperationService_ExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileOperationService_ServiceDesc.Streams[0], FileOperationService_Execute_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &fileOperationServiceExecuteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileOperationService_ExecuteClient interface {
	Recv() (*FileOperationUpdate, error)
	grpc.ClientStream
}

type fileOperationServiceExecuteClient struct {
	grpc.ClientStream
}

func (x *fileOperationServiceExecuteClient) Recv() (*FileOperationUpdate, error) {
	m := new(FileOperationUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileOperationServiceServer is the server API for FileOperationService service.
// All implementations must embed UnimplementedFileOperationServiceServer
// for forward compatibility
type FileOperationServiceServer interface {
	Execute(*ExecuteFileOperationRequest, FileOperationService_ExecuteServer) error
	mustEmbedUnimplementedFileOperationServiceServer()
}

// UnimplementedFileOperationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFileOperationServiceServer struct {
}

func (UnimplementedFileOperationServiceServer) Execute(*ExecuteFileOperationRequest, FileOperationService_ExecuteServer) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedFileOperationServiceServer) mustEmbedUnimplementedFileOperationServiceServer() {}

// UnsafeFileOperationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileOperationServiceServer will
// result in compilation errors.
type UnsafeFileOperationServiceServer interface {
	mustEmbedUnimplementedFileOperationServiceServer()
}

func RegisterFileOperationServiceServer(s grpc.ServiceRegistrar, srv FileOperationServiceServer) {
	s.RegisterService(&FileOperationService_ServiceDesc, srv)
}

func _FileOperationService_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteFileOperationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileOperationServiceServer).Execute(m, &fileOperationServiceExecuteServer{stream})
}

type FileOperationService_ExecuteServer interface {
	Send(*FileOperationUpdate) error
	grpc.ServerStream
}

type fileOperationServiceExecuteServer struct {
	grpc.ServerStream
}

func (x *fileOperationServiceExecuteServer) Send(m *FileOperationUpdate) error {
	return x.ServerStream.SendMsg(m)
}

// FileOperationService_ServiceDesc is the grpc.ServiceDesc for FileOperationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileOperationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file_operation.FileOperationService",
	HandlerType: (*FileOperationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _FileOperationService_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "file_operation.proto",
}
