// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.0
// source: job_restore.proto

package entity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RestoreJobService_Create_FullMethodName       = "/job_restore.RestoreJobService/Create"
	RestoreJobService_RestoreMedia_FullMethodName = "/job_restore.RestoreJobService/RestoreMedia"
	RestoreJobService_GetProgress_FullMethodName  = "/job_restore.RestoreJobService/GetProgress"
	RestoreJobService_ListMedia_FullMethodName    = "/job_restore.RestoreJobService/ListMedia"
	RestoreJobService_ListFiles_FullMethodName    = "/job_restore.RestoreJobService/ListFiles"
)

// RestoreJobServiceClient is the client API for RestoreJobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestoreJobServiceClient interface {
	Create(ctx context.Context, in *CreateRestoreJobRequest, opts ...grpc.CallOption) (*CreateRestoreJobReply, error)
	RestoreMedia(ctx context.Context, in *RestoreMediaRequest, opts ...grpc.CallOption) (*RestoreMediaReply, error)
	GetProgress(ctx context.Context, in *GetRestoreJobProgressRequest, opts ...grpc.CallOption) (*GetRestoreJobProgressReply, error)
	ListMedia(ctx context.Context, in *ListRestoreJobMediaRequest, opts ...grpc.CallOption) (*ListRestoreJobMediaReply, error)
	ListFiles(ctx context.Context, in *ListRestoreJobFilesRequest, opts ...grpc.CallOption) (*ListRestoreJobFilesReply, error)
}

type restoreJobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestoreJobServiceClient(cc grpc.ClientConnInterface) RestoreJobServiceClient {
	return &restoreJobServiceClient{cc}
}

func (c *restoreJobServiceClient) Create(ctx context.Context, in *CreateRestoreJobRequest, opts ...grpc.CallOption) (*CreateRestoreJobReply, error) {
	out := new(CreateRestoreJobReply)
	err := c.cc.Invoke(ctx, RestoreJobService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restoreJobServiceClient) RestoreMedia(ctx context.Context, in *RestoreMediaRequest, opts ...grpc.CallOption) (*RestoreMediaReply, error) {
	out := new(RestoreMediaReply)
	err := c.cc.Invoke(ctx, RestoreJobService_RestoreMedia_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restoreJobServiceClient) GetProgress(ctx context.Context, in *GetRestoreJobProgressRequest, opts ...grpc.CallOption) (*GetRestoreJobProgressReply, error) {
	out := new(GetRestoreJobProgressReply)
	err := c.cc.Invoke(ctx, RestoreJobService_GetProgress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restoreJobServiceClient) ListMedia(ctx context.Context, in *ListRestoreJobMediaRequest, opts ...grpc.CallOption) (*ListRestoreJobMediaReply, error) {
	out := new(ListRestoreJobMediaReply)
	err := c.cc.Invoke(ctx, RestoreJobService_ListMedia_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restoreJobServiceClient) ListFiles(ctx context.Context, in *ListRestoreJobFilesRequest, opts ...grpc.CallOption) (*ListRestoreJobFilesReply, error) {
	out := new(ListRestoreJobFilesReply)
	err := c.cc.Invoke(ctx, RestoreJobService_ListFiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestoreJobServiceServer is the server API for RestoreJobService service.
// All implementations must embed UnimplementedRestoreJobServiceServer
// for forward compatibility
type RestoreJobServiceServer interface {
	Create(context.Context, *CreateRestoreJobRequest) (*CreateRestoreJobReply, error)
	RestoreMedia(context.Context, *RestoreMediaRequest) (*RestoreMediaReply, error)
	GetProgress(context.Context, *GetRestoreJobProgressRequest) (*GetRestoreJobProgressReply, error)
	ListMedia(context.Context, *ListRestoreJobMediaRequest) (*ListRestoreJobMediaReply, error)
	ListFiles(context.Context, *ListRestoreJobFilesRequest) (*ListRestoreJobFilesReply, error)
	mustEmbedUnimplementedRestoreJobServiceServer()
}

// UnimplementedRestoreJobServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRestoreJobServiceServer struct {
}

func (UnimplementedRestoreJobServiceServer) Create(context.Context, *CreateRestoreJobRequest) (*CreateRestoreJobReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRestoreJobServiceServer) RestoreMedia(context.Context, *RestoreMediaRequest) (*RestoreMediaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreMedia not implemented")
}
func (UnimplementedRestoreJobServiceServer) GetProgress(context.Context, *GetRestoreJobProgressRequest) (*GetRestoreJobProgressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProgress not implemented")
}
func (UnimplementedRestoreJobServiceServer) ListMedia(context.Context, *ListRestoreJobMediaRequest) (*ListRestoreJobMediaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMedia not implemented")
}
func (UnimplementedRestoreJobServiceServer) ListFiles(context.Context, *ListRestoreJobFilesRequest) (*ListRestoreJobFilesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedRestoreJobServiceServer) mustEmbedUnimplementedRestoreJobServiceServer() {}

// UnsafeRestoreJobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestoreJobServiceServer will
// result in compilation errors.
type UnsafeRestoreJobServiceServer interface {
	mustEmbedUnimplementedRestoreJobServiceServer()
}

func RegisterRestoreJobServiceServer(s grpc.ServiceRegistrar, srv RestoreJobServiceServer) {
	s.RegisterService(&RestoreJobService_ServiceDesc, srv)
}

func _RestoreJobService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRestoreJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestoreJobServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestoreJobService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestoreJobServiceServer).Create(ctx, req.(*CreateRestoreJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestoreJobService_RestoreMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestoreJobServiceServer).RestoreMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestoreJobService_RestoreMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestoreJobServiceServer).RestoreMedia(ctx, req.(*RestoreMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestoreJobService_GetProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestoreJobProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestoreJobServiceServer).GetProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestoreJobService_GetProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestoreJobServiceServer).GetProgress(ctx, req.(*GetRestoreJobProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestoreJobService_ListMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRestoreJobMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestoreJobServiceServer).ListMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestoreJobService_ListMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestoreJobServiceServer).ListMedia(ctx, req.(*ListRestoreJobMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestoreJobService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRestoreJobFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestoreJobServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestoreJobService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestoreJobServiceServer).ListFiles(ctx, req.(*ListRestoreJobFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestoreJobService_ServiceDesc is the grpc.ServiceDesc for RestoreJobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestoreJobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "job_restore.RestoreJobService",
	HandlerType: (*RestoreJobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _RestoreJobService_Create_Handler,
		},
		{
			MethodName: "RestoreMedia",
			Handler:    _RestoreJobService_RestoreMedia_Handler,
		},
		{
			MethodName: "GetProgress",
			Handler:    _RestoreJobService_GetProgress_Handler,
		},
		{
			MethodName: "ListMedia",
			Handler:    _RestoreJobService_ListMedia_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _RestoreJobService_ListFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job_restore.proto",
}
