syntax = "proto3";
package job_archive;
option go_package = "github.com/samuelncui/yatm/entity";

import "progress.proto";
import "copy_status.proto";
import "job.proto";
import "job_storage.proto";
import "media.proto";

service ArchiveJobService {
    rpc Create(CreateArchiveJobRequest) returns (CreateArchiveJobReply) {}
    rpc WriteMedia(WriteArchiveMediaRequest) returns (WriteArchiveMediaReply) {}
    rpc GetProgress(GetArchiveJobProgressRequest) returns (GetArchiveJobProgressReply) {}
    rpc ListFiles(ListArchiveJobFilesRequest) returns (ListArchiveJobFilesReply) {}
}

message ArchiveFile {
    string source_path = 1;
    string media_path = 2;
    string target_path = 3;
    yatm.job_storage.ExpectedFile expected = 4;
}

message ArchiveItem {
    int64 id = 1;
    copy_status.CopyStatus status = 2;
    int64 size = 3;
    optional int64 media_id = 4;
    ArchiveFile file = 5;
}

message CreateArchiveJobRequest {
    int64 priority = 1;
    yatm.job_storage.ArchiveJobSpec spec = 2;
    bool force_rehash = 4;
    yatm.job_storage.PreviewPolicy preview_policy = 6;
}

message CreateArchiveJobReply {
    job.Job job = 1;
}

message WriteArchiveMediaRequest {
    int64 id = 1;
    media.ArchiveMediaTarget target = 2;
}

message WriteArchiveMediaReply {}

message GetArchiveJobProgressRequest {
    int64 id = 1;
}

message GetArchiveJobProgressReply {
    progress.Progress progress = 1;
    int64 preview_job_id = 2;
    string preview_error = 3;
}

message ListArchiveJobFilesRequest {
    int64 id = 1;
    int32 limit = 2;
    optional int64 offset = 3;
    repeated copy_status.CopyStatus filter_status = 4;
}

message ListArchiveJobFilesReply {
    repeated ArchiveItem items = 1;
}
