// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: preview.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreviewManifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileSignature []byte          `protobuf:"bytes,1,opt,name=file_signature,json=fileSignature,proto3" json:"file_signature,omitempty"`
	Generator     string          `protobuf:"bytes,2,opt,name=generator,proto3" json:"generator,omitempty"`
	SettingsJson  []byte          `protobuf:"bytes,3,opt,name=settings_json,json=settingsJson,proto3" json:"settings_json,omitempty"`
	Assets        []*PreviewAsset `protobuf:"bytes,4,rep,name=assets,proto3" json:"assets,omitempty"`
}

func (x *PreviewManifest) Reset() {
	*x = PreviewManifest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_preview_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreviewManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewManifest) ProtoMessage() {}

func (x *PreviewManifest) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewManifest.ProtoReflect.Descriptor instead.
func (*PreviewManifest) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{0}
}

func (x *PreviewManifest) GetFileSignature() []byte {
	if x != nil {
		return x.FileSignature
	}
	return nil
}

func (x *PreviewManifest) GetGenerator() string {
	if x != nil {
		return x.Generator
	}
	return ""
}

func (x *PreviewManifest) GetSettingsJson() []byte {
	if x != nil {
		return x.SettingsJson
	}
	return nil
}

func (x *PreviewManifest) GetAssets() []*PreviewAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type PreviewAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role      string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	MediaType string `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Width     uint32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height    uint32 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *PreviewAsset) Reset() {
	*x = PreviewAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_preview_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreviewAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewAsset) ProtoMessage() {}

func (x *PreviewAsset) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewAsset.ProtoReflect.Descriptor instead.
func (*PreviewAsset) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{1}
}

func (x *PreviewAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PreviewAsset) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PreviewAsset) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *PreviewAsset) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PreviewAsset) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_preview_proto protoreflect.FileDescriptor

var file_preview_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x22, 0xaa, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x6a, 0x73,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x2e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x06, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x23, 0x5a, 0x21, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x6d, 0x75, 0x65, 0x6c,
	0x6e, 0x63, 0x75, 0x69, 0x2f, 0x79, 0x61, 0x74, 0x6d, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_preview_proto_rawDescOnce sync.Once
	file_preview_proto_rawDescData = file_preview_proto_rawDesc
)

func file_preview_proto_rawDescGZIP() []byte {
	file_preview_proto_rawDescOnce.Do(func() {
		file_preview_proto_rawDescData = protoimpl.X.CompressGZIP(file_preview_proto_rawDescData)
	})
	return file_preview_proto_rawDescData
}

var file_preview_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_preview_proto_goTypes = []interface{}{
	(*PreviewManifest)(nil), // 0: preview.PreviewManifest
	(*PreviewAsset)(nil),    // 1: preview.PreviewAsset
}
var file_preview_proto_depIdxs = []int32{
	1, // 0: preview.PreviewManifest.assets:type_name -> preview.PreviewAsset
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_preview_proto_init() }
func file_preview_proto_init() {
	if File_preview_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_preview_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreviewManifest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_preview_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreviewAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_preview_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_preview_proto_goTypes,
		DependencyIndexes: file_preview_proto_depIdxs,
		MessageInfos:      file_preview_proto_msgTypes,
	}.Build()
	File_preview_proto = out.File
	file_preview_proto_rawDesc = nil
	file_preview_proto_goTypes = nil
	file_preview_proto_depIdxs = nil
}
