// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "job_storage.proto" (package "yatm.job_storage", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StoragePosition } from "./storage";
import { FileSelection } from "./file";
import { Source } from "./source";
/**
 * @generated from protobuf message yatm.job_storage.ArchiveJobSpec
 */
export interface ArchiveJobSpec {
    /**
     * @generated from protobuf field: repeated source.Source sources = 1
     */
    sources: Source[];
    /**
     * @generated from protobuf field: repeated int64 file_ids = 2
     */
    fileIds: bigint[];
    /**
     * @generated from protobuf field: repeated file.FileSelection selections = 3
     */
    selections: FileSelection[];
}
/**
 * @generated from protobuf message yatm.job_storage.RestoreJobSpec
 */
export interface RestoreJobSpec {
    /**
     * @generated from protobuf field: repeated int64 file_version_ids = 2
     */
    fileVersionIds: bigint[];
    /**
     * @generated from protobuf field: repeated file.FileSelection selections = 3
     */
    selections: FileSelection[];
    /**
     * @generated from protobuf field: yatm.job_storage.RestoreDestination destination = 4
     */
    destination?: RestoreDestination;
    /**
     * @generated from protobuf field: bool allow_damaged_copies = 5
     */
    allowDamagedCopies: boolean;
    /**
     * @generated from protobuf field: yatm.job_storage.RestoreVersionPolicy version_policy = 6
     */
    versionPolicy?: RestoreVersionPolicy;
    /**
     * Explicit consent to omit automatic selections with no matching dated version.
     *
     * @generated from protobuf field: bool skip_unmatched_versions = 7
     */
    skipUnmatchedVersions: boolean;
}
/**
 * Unset cutoff selects the latest saved version. Explicit version IDs override this policy.
 *
 * @generated from protobuf message yatm.job_storage.RestoreVersionPolicy
 */
export interface RestoreVersionPolicy {
    /**
     * @generated from protobuf field: optional int64 before_at_ms = 1
     */
    beforeAtMs?: bigint;
}
/**
 * The server resolves and freezes root_path/executor_id when the Job is created.
 *
 * @generated from protobuf message yatm.job_storage.RestoreDestination
 */
export interface RestoreDestination {
    /**
     * @generated from protobuf field: int64 location_id = 1
     */
    locationId: bigint;
    /**
     * @generated from protobuf field: string path = 2
     */
    path: string;
    /**
     * @generated from protobuf field: string root_path = 3
     */
    rootPath: string;
    /**
     * @generated from protobuf field: string executor_id = 4
     */
    executorId: string;
    /**
     * @generated from protobuf field: string binding_token = 5
     */
    bindingToken: string;
}
/**
 * ArchiveManifestFile is stored only in an Archive Job database.
 *
 * @generated from protobuf message yatm.job_storage.ArchiveManifestFile
 */
export interface ArchiveManifestFile {
    /**
     * @generated from protobuf field: string source_path = 1
     */
    sourcePath: string;
    /**
     * @generated from protobuf field: yatm.job_storage.ExpectedFile expected = 3
     */
    expected?: ExpectedFile;
    /**
     * @generated from protobuf field: bool library_selected = 4
     */
    librarySelected: boolean;
}
/**
 * ExpectedFile freezes selected content identity without interpreting its signature.
 *
 * @generated from protobuf message yatm.job_storage.ExpectedFile
 */
export interface ExpectedFile {
    /**
     * @generated from protobuf field: int64 file_id = 1
     */
    fileId: bigint;
    /**
     * @generated from protobuf field: bytes signature = 2
     */
    signature: Uint8Array;
    /**
     * @generated from protobuf field: bytes sha256 = 3
     */
    sha256: Uint8Array;
    /**
     * @generated from protobuf field: int64 size = 4
     */
    size: bigint;
    /**
     * @generated from protobuf field: int64 file_version_id = 5
     */
    fileVersionId: bigint;
    /**
     * @generated from protobuf field: uint32 mode = 6
     */
    mode: number;
    /**
     * @generated from protobuf field: int64 mtime_ns = 7
     */
    mtimeNs: bigint;
    /**
     * Navigation provenance captured with the original observation, not content identity.
     *
     * @generated from protobuf field: int64 original_location_id = 8
     */
    originalLocationId: bigint;
}
/**
 * ArchiveCopyResult is staged after one file is copied and verified.
 *
 * @generated from protobuf message yatm.job_storage.ArchiveCopyResult
 */
export interface ArchiveCopyResult {
    /**
     * @generated from protobuf field: int64 size = 1
     */
    size: bigint;
    /**
     * @generated from protobuf field: uint32 mode = 2
     */
    mode: number;
    /**
     * @generated from protobuf field: int64 mod_time_ns = 3
     */
    modTimeNs: bigint;
    /**
     * @generated from protobuf field: int64 write_time_ns = 4
     */
    writeTimeNs: bigint;
    /**
     * @generated from protobuf field: bytes sha256 = 5
     */
    sha256: Uint8Array;
    /**
     * @generated from protobuf field: yatm.storage.StoragePosition storage = 6
     */
    storage?: StoragePosition;
}
/**
 * @generated from protobuf enum yatm.job_storage.PreviewPolicy
 */
export enum PreviewPolicy {
    /**
     * @generated from protobuf enum value: PREVIEW_NONE = 0;
     */
    PREVIEW_NONE = 0,
    /**
     * @generated from protobuf enum value: PREVIEW_MISSING_ONLY = 1;
     */
    PREVIEW_MISSING_ONLY = 1,
    /**
     * @generated from protobuf enum value: PREVIEW_REGENERATE_ALL = 2;
     */
    PREVIEW_REGENERATE_ALL = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class ArchiveJobSpec$Type extends MessageType<ArchiveJobSpec> {
    constructor() {
        super("yatm.job_storage.ArchiveJobSpec", [
            { no: 1, name: "sources", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Source },
            { no: 2, name: "file_ids", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "selections", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => FileSelection }
        ]);
    }
    create(value?: PartialMessage<ArchiveJobSpec>): ArchiveJobSpec {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sources = [];
        message.fileIds = [];
        message.selections = [];
        if (value !== undefined)
            reflectionMergePartial<ArchiveJobSpec>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ArchiveJobSpec): ArchiveJobSpec {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated source.Source sources */ 1:
                    message.sources.push(Source.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated int64 file_ids */ 2:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.fileIds.push(reader.int64().toBigInt());
                    else
                        message.fileIds.push(reader.int64().toBigInt());
                    break;
                case /* repeated file.FileSelection selections */ 3:
                    message.selections.push(FileSelection.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ArchiveJobSpec, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated source.Source sources = 1; */
        for (let i = 0; i < message.sources.length; i++)
            Source.internalBinaryWrite(message.sources[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated int64 file_ids = 2; */
        if (message.fileIds.length) {
            writer.tag(2, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.fileIds.length; i++)
                writer.int64(message.fileIds[i]);
            writer.join();
        }
        /* repeated file.FileSelection selections = 3; */
        for (let i = 0; i < message.selections.length; i++)
            FileSelection.internalBinaryWrite(message.selections[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.job_storage.ArchiveJobSpec
 */
export const ArchiveJobSpec = new ArchiveJobSpec$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RestoreJobSpec$Type extends MessageType<RestoreJobSpec> {
    constructor() {
        super("yatm.job_storage.RestoreJobSpec", [
            { no: 2, name: "file_version_ids", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "selections", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => FileSelection },
            { no: 4, name: "destination", kind: "message", T: () => RestoreDestination },
            { no: 5, name: "allow_damaged_copies", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "version_policy", kind: "message", T: () => RestoreVersionPolicy },
            { no: 7, name: "skip_unmatched_versions", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<RestoreJobSpec>): RestoreJobSpec {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fileVersionIds = [];
        message.selections = [];
        message.allowDamagedCopies = false;
        message.skipUnmatchedVersions = false;
        if (value !== undefined)
            reflectionMergePartial<RestoreJobSpec>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RestoreJobSpec): RestoreJobSpec {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated int64 file_version_ids */ 2:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.fileVersionIds.push(reader.int64().toBigInt());
                    else
                        message.fileVersionIds.push(reader.int64().toBigInt());
                    break;
                case /* repeated file.FileSelection selections */ 3:
                    message.selections.push(FileSelection.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* yatm.job_storage.RestoreDestination destination */ 4:
                    message.destination = RestoreDestination.internalBinaryRead(reader, reader.uint32(), options, message.destination);
                    break;
                case /* bool allow_damaged_copies */ 5:
                    message.allowDamagedCopies = reader.bool();
                    break;
                case /* yatm.job_storage.RestoreVersionPolicy version_policy */ 6:
                    message.versionPolicy = RestoreVersionPolicy.internalBinaryRead(reader, reader.uint32(), options, message.versionPolicy);
                    break;
                case /* bool skip_unmatched_versions */ 7:
                    message.skipUnmatchedVersions = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RestoreJobSpec, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated int64 file_version_ids = 2; */
        if (message.fileVersionIds.length) {
            writer.tag(2, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.fileVersionIds.length; i++)
                writer.int64(message.fileVersionIds[i]);
            writer.join();
        }
        /* repeated file.FileSelection selections = 3; */
        for (let i = 0; i < message.selections.length; i++)
            FileSelection.internalBinaryWrite(message.selections[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* yatm.job_storage.RestoreDestination destination = 4; */
        if (message.destination)
            RestoreDestination.internalBinaryWrite(message.destination, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* bool allow_damaged_copies = 5; */
        if (message.allowDamagedCopies !== false)
            writer.tag(5, WireType.Varint).bool(message.allowDamagedCopies);
        /* yatm.job_storage.RestoreVersionPolicy version_policy = 6; */
        if (message.versionPolicy)
            RestoreVersionPolicy.internalBinaryWrite(message.versionPolicy, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* bool skip_unmatched_versions = 7; */
        if (message.skipUnmatchedVersions !== false)
            writer.tag(7, WireType.Varint).bool(message.skipUnmatchedVersions);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.job_storage.RestoreJobSpec
 */
export const RestoreJobSpec = new RestoreJobSpec$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RestoreVersionPolicy$Type extends MessageType<RestoreVersionPolicy> {
    constructor() {
        super("yatm.job_storage.RestoreVersionPolicy", [
            { no: 1, name: "before_at_ms", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<RestoreVersionPolicy>): RestoreVersionPolicy {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RestoreVersionPolicy>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RestoreVersionPolicy): RestoreVersionPolicy {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional int64 before_at_ms */ 1:
                    message.beforeAtMs = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RestoreVersionPolicy, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional int64 before_at_ms = 1; */
        if (message.beforeAtMs !== undefined)
            writer.tag(1, WireType.Varint).int64(message.beforeAtMs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.job_storage.RestoreVersionPolicy
 */
export const RestoreVersionPolicy = new RestoreVersionPolicy$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RestoreDestination$Type extends MessageType<RestoreDestination> {
    constructor() {
        super("yatm.job_storage.RestoreDestination", [
            { no: 1, name: "location_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "root_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "executor_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "binding_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RestoreDestination>): RestoreDestination {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.locationId = 0n;
        message.path = "";
        message.rootPath = "";
        message.executorId = "";
        message.bindingToken = "";
        if (value !== undefined)
            reflectionMergePartial<RestoreDestination>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RestoreDestination): RestoreDestination {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 location_id */ 1:
                    message.locationId = reader.int64().toBigInt();
                    break;
                case /* string path */ 2:
                    message.path = reader.string();
                    break;
                case /* string root_path */ 3:
                    message.rootPath = reader.string();
                    break;
                case /* string executor_id */ 4:
                    message.executorId = reader.string();
                    break;
                case /* string binding_token */ 5:
                    message.bindingToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RestoreDestination, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 location_id = 1; */
        if (message.locationId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.locationId);
        /* string path = 2; */
        if (message.path !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.path);
        /* string root_path = 3; */
        if (message.rootPath !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.rootPath);
        /* string executor_id = 4; */
        if (message.executorId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.executorId);
        /* string binding_token = 5; */
        if (message.bindingToken !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.bindingToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.job_storage.RestoreDestination
 */
export const RestoreDestination = new RestoreDestination$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ArchiveManifestFile$Type extends MessageType<ArchiveManifestFile> {
    constructor() {
        super("yatm.job_storage.ArchiveManifestFile", [
            { no: 1, name: "source_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "expected", kind: "message", T: () => ExpectedFile },
            { no: 4, name: "library_selected", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ArchiveManifestFile>): ArchiveManifestFile {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sourcePath = "";
        message.librarySelected = false;
        if (value !== undefined)
            reflectionMergePartial<ArchiveManifestFile>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ArchiveManifestFile): ArchiveManifestFile {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string source_path */ 1:
                    message.sourcePath = reader.string();
                    break;
                case /* yatm.job_storage.ExpectedFile expected */ 3:
                    message.expected = ExpectedFile.internalBinaryRead(reader, reader.uint32(), options, message.expected);
                    break;
                case /* bool library_selected */ 4:
                    message.librarySelected = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ArchiveManifestFile, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string source_path = 1; */
        if (message.sourcePath !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.sourcePath);
        /* yatm.job_storage.ExpectedFile expected = 3; */
        if (message.expected)
            ExpectedFile.internalBinaryWrite(message.expected, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* bool library_selected = 4; */
        if (message.librarySelected !== false)
            writer.tag(4, WireType.Varint).bool(message.librarySelected);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.job_storage.ArchiveManifestFile
 */
export const ArchiveManifestFile = new ArchiveManifestFile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ExpectedFile$Type extends MessageType<ExpectedFile> {
    constructor() {
        super("yatm.job_storage.ExpectedFile", [
            { no: 1, name: "file_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 3, name: "sha256", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 4, name: "size", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "file_version_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 6, name: "mode", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "mtime_ns", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 8, name: "original_location_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<ExpectedFile>): ExpectedFile {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fileId = 0n;
        message.signature = new Uint8Array(0);
        message.sha256 = new Uint8Array(0);
        message.size = 0n;
        message.fileVersionId = 0n;
        message.mode = 0;
        message.mtimeNs = 0n;
        message.originalLocationId = 0n;
        if (value !== undefined)
            reflectionMergePartial<ExpectedFile>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExpectedFile): ExpectedFile {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 file_id */ 1:
                    message.fileId = reader.int64().toBigInt();
                    break;
                case /* bytes signature */ 2:
                    message.signature = reader.bytes();
                    break;
                case /* bytes sha256 */ 3:
                    message.sha256 = reader.bytes();
                    break;
                case /* int64 size */ 4:
                    message.size = reader.int64().toBigInt();
                    break;
                case /* int64 file_version_id */ 5:
                    message.fileVersionId = reader.int64().toBigInt();
                    break;
                case /* uint32 mode */ 6:
                    message.mode = reader.uint32();
                    break;
                case /* int64 mtime_ns */ 7:
                    message.mtimeNs = reader.int64().toBigInt();
                    break;
                case /* int64 original_location_id */ 8:
                    message.originalLocationId = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ExpectedFile, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 file_id = 1; */
        if (message.fileId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.fileId);
        /* bytes signature = 2; */
        if (message.signature.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.signature);
        /* bytes sha256 = 3; */
        if (message.sha256.length)
            writer.tag(3, WireType.LengthDelimited).bytes(message.sha256);
        /* int64 size = 4; */
        if (message.size !== 0n)
            writer.tag(4, WireType.Varint).int64(message.size);
        /* int64 file_version_id = 5; */
        if (message.fileVersionId !== 0n)
            writer.tag(5, WireType.Varint).int64(message.fileVersionId);
        /* uint32 mode = 6; */
        if (message.mode !== 0)
            writer.tag(6, WireType.Varint).uint32(message.mode);
        /* int64 mtime_ns = 7; */
        if (message.mtimeNs !== 0n)
            writer.tag(7, WireType.Varint).int64(message.mtimeNs);
        /* int64 original_location_id = 8; */
        if (message.originalLocationId !== 0n)
            writer.tag(8, WireType.Varint).int64(message.originalLocationId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.job_storage.ExpectedFile
 */
export const ExpectedFile = new ExpectedFile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ArchiveCopyResult$Type extends MessageType<ArchiveCopyResult> {
    constructor() {
        super("yatm.job_storage.ArchiveCopyResult", [
            { no: 1, name: "size", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "mode", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "mod_time_ns", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "write_time_ns", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "sha256", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 6, name: "storage", kind: "message", T: () => StoragePosition }
        ]);
    }
    create(value?: PartialMessage<ArchiveCopyResult>): ArchiveCopyResult {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.size = 0n;
        message.mode = 0;
        message.modTimeNs = 0n;
        message.writeTimeNs = 0n;
        message.sha256 = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<ArchiveCopyResult>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ArchiveCopyResult): ArchiveCopyResult {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 size */ 1:
                    message.size = reader.int64().toBigInt();
                    break;
                case /* uint32 mode */ 2:
                    message.mode = reader.uint32();
                    break;
                case /* int64 mod_time_ns */ 3:
                    message.modTimeNs = reader.int64().toBigInt();
                    break;
                case /* int64 write_time_ns */ 4:
                    message.writeTimeNs = reader.int64().toBigInt();
                    break;
                case /* bytes sha256 */ 5:
                    message.sha256 = reader.bytes();
                    break;
                case /* yatm.storage.StoragePosition storage */ 6:
                    message.storage = StoragePosition.internalBinaryRead(reader, reader.uint32(), options, message.storage);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ArchiveCopyResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 size = 1; */
        if (message.size !== 0n)
            writer.tag(1, WireType.Varint).int64(message.size);
        /* uint32 mode = 2; */
        if (message.mode !== 0)
            writer.tag(2, WireType.Varint).uint32(message.mode);
        /* int64 mod_time_ns = 3; */
        if (message.modTimeNs !== 0n)
            writer.tag(3, WireType.Varint).int64(message.modTimeNs);
        /* int64 write_time_ns = 4; */
        if (message.writeTimeNs !== 0n)
            writer.tag(4, WireType.Varint).int64(message.writeTimeNs);
        /* bytes sha256 = 5; */
        if (message.sha256.length)
            writer.tag(5, WireType.LengthDelimited).bytes(message.sha256);
        /* yatm.storage.StoragePosition storage = 6; */
        if (message.storage)
            StoragePosition.internalBinaryWrite(message.storage, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.job_storage.ArchiveCopyResult
 */
export const ArchiveCopyResult = new ArchiveCopyResult$Type();
