// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "job_archive.proto" (package "job_archive", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ArchiveJobService } from "./job_archive";
import type { ListArchiveJobFilesReply } from "./job_archive";
import type { ListArchiveJobFilesRequest } from "./job_archive";
import type { GetArchiveJobProgressReply } from "./job_archive";
import type { GetArchiveJobProgressRequest } from "./job_archive";
import type { WriteArchiveMediaReply } from "./job_archive";
import type { WriteArchiveMediaRequest } from "./job_archive";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateArchiveJobReply } from "./job_archive";
import type { CreateArchiveJobRequest } from "./job_archive";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service job_archive.ArchiveJobService
 */
export interface IArchiveJobServiceClient {
    /**
     * @generated from protobuf rpc: Create
     */
    create(input: CreateArchiveJobRequest, options?: RpcOptions): UnaryCall<CreateArchiveJobRequest, CreateArchiveJobReply>;
    /**
     * @generated from protobuf rpc: WriteMedia
     */
    writeMedia(input: WriteArchiveMediaRequest, options?: RpcOptions): UnaryCall<WriteArchiveMediaRequest, WriteArchiveMediaReply>;
    /**
     * @generated from protobuf rpc: GetProgress
     */
    getProgress(input: GetArchiveJobProgressRequest, options?: RpcOptions): UnaryCall<GetArchiveJobProgressRequest, GetArchiveJobProgressReply>;
    /**
     * @generated from protobuf rpc: ListFiles
     */
    listFiles(input: ListArchiveJobFilesRequest, options?: RpcOptions): UnaryCall<ListArchiveJobFilesRequest, ListArchiveJobFilesReply>;
}
/**
 * @generated from protobuf service job_archive.ArchiveJobService
 */
export class ArchiveJobServiceClient implements IArchiveJobServiceClient, ServiceInfo {
    typeName = ArchiveJobService.typeName;
    methods = ArchiveJobService.methods;
    options = ArchiveJobService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Create
     */
    create(input: CreateArchiveJobRequest, options?: RpcOptions): UnaryCall<CreateArchiveJobRequest, CreateArchiveJobReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateArchiveJobRequest, CreateArchiveJobReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: WriteMedia
     */
    writeMedia(input: WriteArchiveMediaRequest, options?: RpcOptions): UnaryCall<WriteArchiveMediaRequest, WriteArchiveMediaReply> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<WriteArchiveMediaRequest, WriteArchiveMediaReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetProgress
     */
    getProgress(input: GetArchiveJobProgressRequest, options?: RpcOptions): UnaryCall<GetArchiveJobProgressRequest, GetArchiveJobProgressReply> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetArchiveJobProgressRequest, GetArchiveJobProgressReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListFiles
     */
    listFiles(input: ListArchiveJobFilesRequest, options?: RpcOptions): UnaryCall<ListArchiveJobFilesRequest, ListArchiveJobFilesReply> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListArchiveJobFilesRequest, ListArchiveJobFilesReply>("unary", this._transport, method, opt, input);
    }
}
