// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "job_restore.proto" (package "yatm.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { RestoreJobService } from "./job_restore";
import type { ListRestoreJobFilesResponse } from "./job_restore";
import type { ListRestoreJobFilesRequest } from "./job_restore";
import type { ListRestoreJobMediaResponse } from "./job_restore";
import type { ListRestoreJobMediaRequest } from "./job_restore";
import type { GetRestoreJobProgressResponse } from "./job_restore";
import type { GetRestoreJobProgressRequest } from "./job_restore";
import type { RestoreMediaResponse } from "./job_restore";
import type { RestoreMediaRequest } from "./job_restore";
import type { GetRestoreJobCreationResponse } from "./job_restore";
import type { GetRestoreJobCreationRequest } from "./job_restore";
import type { CreateRestoreJobResponse } from "./job_restore";
import type { CreateRestoreJobRequest } from "./job_restore";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { EstimateRestoreJobResponse } from "./job_restore";
import type { EstimateRestoreJobRequest } from "./job_restore";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service yatm.v1.RestoreJobService
 */
export interface IRestoreJobServiceClient {
    /**
     * @generated from protobuf rpc: Estimate
     */
    estimate(input: EstimateRestoreJobRequest, options?: RpcOptions): UnaryCall<EstimateRestoreJobRequest, EstimateRestoreJobResponse>;
    /**
     * @generated from protobuf rpc: Create
     */
    create(input: CreateRestoreJobRequest, options?: RpcOptions): UnaryCall<CreateRestoreJobRequest, CreateRestoreJobResponse>;
    /**
     * @generated from protobuf rpc: GetCreation
     */
    getCreation(input: GetRestoreJobCreationRequest, options?: RpcOptions): UnaryCall<GetRestoreJobCreationRequest, GetRestoreJobCreationResponse>;
    /**
     * @generated from protobuf rpc: RestoreMedia
     */
    restoreMedia(input: RestoreMediaRequest, options?: RpcOptions): UnaryCall<RestoreMediaRequest, RestoreMediaResponse>;
    /**
     * @generated from protobuf rpc: GetProgress
     */
    getProgress(input: GetRestoreJobProgressRequest, options?: RpcOptions): UnaryCall<GetRestoreJobProgressRequest, GetRestoreJobProgressResponse>;
    /**
     * @generated from protobuf rpc: ListMedia
     */
    listMedia(input: ListRestoreJobMediaRequest, options?: RpcOptions): UnaryCall<ListRestoreJobMediaRequest, ListRestoreJobMediaResponse>;
    /**
     * @generated from protobuf rpc: ListFiles
     */
    listFiles(input: ListRestoreJobFilesRequest, options?: RpcOptions): UnaryCall<ListRestoreJobFilesRequest, ListRestoreJobFilesResponse>;
}
/**
 * @generated from protobuf service yatm.v1.RestoreJobService
 */
export class RestoreJobServiceClient implements IRestoreJobServiceClient, ServiceInfo {
    typeName = RestoreJobService.typeName;
    methods = RestoreJobService.methods;
    options = RestoreJobService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Estimate
     */
    estimate(input: EstimateRestoreJobRequest, options?: RpcOptions): UnaryCall<EstimateRestoreJobRequest, EstimateRestoreJobResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<EstimateRestoreJobRequest, EstimateRestoreJobResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Create
     */
    create(input: CreateRestoreJobRequest, options?: RpcOptions): UnaryCall<CreateRestoreJobRequest, CreateRestoreJobResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateRestoreJobRequest, CreateRestoreJobResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCreation
     */
    getCreation(input: GetRestoreJobCreationRequest, options?: RpcOptions): UnaryCall<GetRestoreJobCreationRequest, GetRestoreJobCreationResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRestoreJobCreationRequest, GetRestoreJobCreationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RestoreMedia
     */
    restoreMedia(input: RestoreMediaRequest, options?: RpcOptions): UnaryCall<RestoreMediaRequest, RestoreMediaResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<RestoreMediaRequest, RestoreMediaResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetProgress
     */
    getProgress(input: GetRestoreJobProgressRequest, options?: RpcOptions): UnaryCall<GetRestoreJobProgressRequest, GetRestoreJobProgressResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRestoreJobProgressRequest, GetRestoreJobProgressResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListMedia
     */
    listMedia(input: ListRestoreJobMediaRequest, options?: RpcOptions): UnaryCall<ListRestoreJobMediaRequest, ListRestoreJobMediaResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListRestoreJobMediaRequest, ListRestoreJobMediaResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListFiles
     */
    listFiles(input: ListRestoreJobFilesRequest, options?: RpcOptions): UnaryCall<ListRestoreJobFilesRequest, ListRestoreJobFilesResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListRestoreJobFilesRequest, ListRestoreJobFilesResponse>("unary", this._transport, method, opt, input);
    }
}
