// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "job_archive.proto" (package "job_archive", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Progress } from "./progress";
import { ArchiveMediaTarget } from "./media";
import { Job } from "./job";
import { PreviewPolicy } from "./job_storage";
import { ArchiveJobSpec } from "./job_storage";
import { CopyStatus } from "./copy_status";
import { ExpectedFile } from "./job_storage";
/**
 * @generated from protobuf message job_archive.ArchiveFile
 */
export interface ArchiveFile {
    /**
     * @generated from protobuf field: string source_path = 1
     */
    sourcePath: string;
    /**
     * @generated from protobuf field: string media_path = 2
     */
    mediaPath: string;
    /**
     * @generated from protobuf field: string target_path = 3
     */
    targetPath: string;
    /**
     * @generated from protobuf field: yatm.job_storage.ExpectedFile expected = 4
     */
    expected?: ExpectedFile;
}
/**
 * @generated from protobuf message job_archive.ArchiveItem
 */
export interface ArchiveItem {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: bigint;
    /**
     * @generated from protobuf field: copy_status.CopyStatus status = 2
     */
    status: CopyStatus;
    /**
     * @generated from protobuf field: int64 size = 3
     */
    size: bigint;
    /**
     * @generated from protobuf field: optional int64 media_id = 4
     */
    mediaId?: bigint;
    /**
     * @generated from protobuf field: job_archive.ArchiveFile file = 5
     */
    file?: ArchiveFile;
}
/**
 * @generated from protobuf message job_archive.CreateArchiveJobRequest
 */
export interface CreateArchiveJobRequest {
    /**
     * @generated from protobuf field: int64 priority = 1
     */
    priority: bigint;
    /**
     * @generated from protobuf field: yatm.job_storage.ArchiveJobSpec spec = 2
     */
    spec?: ArchiveJobSpec;
    /**
     * @generated from protobuf field: bool force_rehash = 4
     */
    forceRehash: boolean;
    /**
     * @generated from protobuf field: yatm.job_storage.PreviewPolicy preview_policy = 6
     */
    previewPolicy: PreviewPolicy;
}
/**
 * @generated from protobuf message job_archive.CreateArchiveJobReply
 */
export interface CreateArchiveJobReply {
    /**
     * @generated from protobuf field: job.Job job = 1
     */
    job?: Job;
}
/**
 * @generated from protobuf message job_archive.WriteArchiveMediaRequest
 */
export interface WriteArchiveMediaRequest {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: bigint;
    /**
     * @generated from protobuf field: media.ArchiveMediaTarget target = 2
     */
    target?: ArchiveMediaTarget;
}
/**
 * @generated from protobuf message job_archive.WriteArchiveMediaReply
 */
export interface WriteArchiveMediaReply {
}
/**
 * @generated from protobuf message job_archive.GetArchiveJobProgressRequest
 */
export interface GetArchiveJobProgressRequest {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: bigint;
}
/**
 * @generated from protobuf message job_archive.GetArchiveJobProgressReply
 */
export interface GetArchiveJobProgressReply {
    /**
     * @generated from protobuf field: progress.Progress progress = 1
     */
    progress?: Progress;
    /**
     * @generated from protobuf field: int64 preview_job_id = 2
     */
    previewJobId: bigint;
    /**
     * @generated from protobuf field: string preview_error = 3
     */
    previewError: string;
}
/**
 * @generated from protobuf message job_archive.ListArchiveJobFilesRequest
 */
export interface ListArchiveJobFilesRequest {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: bigint;
    /**
     * @generated from protobuf field: int32 limit = 2
     */
    limit: number;
    /**
     * @generated from protobuf field: optional int64 offset = 3
     */
    offset?: bigint;
    /**
     * @generated from protobuf field: repeated copy_status.CopyStatus filter_status = 4
     */
    filterStatus: CopyStatus[];
}
/**
 * @generated from protobuf message job_archive.ListArchiveJobFilesReply
 */
export interface ListArchiveJobFilesReply {
    /**
     * @generated from protobuf field: repeated job_archive.ArchiveItem items = 1
     */
    items: ArchiveItem[];
}
// @generated message type with reflection information, may provide speed optimized methods
class ArchiveFile$Type extends MessageType<ArchiveFile> {
    constructor() {
        super("job_archive.ArchiveFile", [
            { no: 1, name: "source_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "media_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "target_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "expected", kind: "message", T: () => ExpectedFile }
        ]);
    }
    create(value?: PartialMessage<ArchiveFile>): ArchiveFile {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sourcePath = "";
        message.mediaPath = "";
        message.targetPath = "";
        if (value !== undefined)
            reflectionMergePartial<ArchiveFile>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ArchiveFile): ArchiveFile {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string source_path */ 1:
                    message.sourcePath = reader.string();
                    break;
                case /* string media_path */ 2:
                    message.mediaPath = reader.string();
                    break;
                case /* string target_path */ 3:
                    message.targetPath = reader.string();
                    break;
                case /* yatm.job_storage.ExpectedFile expected */ 4:
                    message.expected = ExpectedFile.internalBinaryRead(reader, reader.uint32(), options, message.expected);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ArchiveFile, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string source_path = 1; */
        if (message.sourcePath !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.sourcePath);
        /* string media_path = 2; */
        if (message.mediaPath !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.mediaPath);
        /* string target_path = 3; */
        if (message.targetPath !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.targetPath);
        /* yatm.job_storage.ExpectedFile expected = 4; */
        if (message.expected)
            ExpectedFile.internalBinaryWrite(message.expected, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message job_archive.ArchiveFile
 */
export const ArchiveFile = new ArchiveFile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ArchiveItem$Type extends MessageType<ArchiveItem> {
    constructor() {
        super("job_archive.ArchiveItem", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "status", kind: "enum", T: () => ["copy_status.CopyStatus", CopyStatus] },
            { no: 3, name: "size", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "media_id", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "file", kind: "message", T: () => ArchiveFile }
        ]);
    }
    create(value?: PartialMessage<ArchiveItem>): ArchiveItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.status = 0;
        message.size = 0n;
        if (value !== undefined)
            reflectionMergePartial<ArchiveItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ArchiveItem): ArchiveItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* copy_status.CopyStatus status */ 2:
                    message.status = reader.int32();
                    break;
                case /* int64 size */ 3:
                    message.size = reader.int64().toBigInt();
                    break;
                case /* optional int64 media_id */ 4:
                    message.mediaId = reader.int64().toBigInt();
                    break;
                case /* job_archive.ArchiveFile file */ 5:
                    message.file = ArchiveFile.internalBinaryRead(reader, reader.uint32(), options, message.file);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ArchiveItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* copy_status.CopyStatus status = 2; */
        if (message.status !== 0)
            writer.tag(2, WireType.Varint).int32(message.status);
        /* int64 size = 3; */
        if (message.size !== 0n)
            writer.tag(3, WireType.Varint).int64(message.size);
        /* optional int64 media_id = 4; */
        if (message.mediaId !== undefined)
            writer.tag(4, WireType.Varint).int64(message.mediaId);
        /* job_archive.ArchiveFile file = 5; */
        if (message.file)
            ArchiveFile.internalBinaryWrite(message.file, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message job_archive.ArchiveItem
 */
export const ArchiveItem = new ArchiveItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateArchiveJobRequest$Type extends MessageType<CreateArchiveJobRequest> {
    constructor() {
        super("job_archive.CreateArchiveJobRequest", [
            { no: 1, name: "priority", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "spec", kind: "message", T: () => ArchiveJobSpec },
            { no: 4, name: "force_rehash", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "preview_policy", kind: "enum", T: () => ["yatm.job_storage.PreviewPolicy", PreviewPolicy] }
        ]);
    }
    create(value?: PartialMessage<CreateArchiveJobRequest>): CreateArchiveJobRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.priority = 0n;
        message.forceRehash = false;
        message.previewPolicy = 0;
        if (value !== undefined)
            reflectionMergePartial<CreateArchiveJobRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateArchiveJobRequest): CreateArchiveJobRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 priority */ 1:
                    message.priority = reader.int64().toBigInt();
                    break;
                case /* yatm.job_storage.ArchiveJobSpec spec */ 2:
                    message.spec = ArchiveJobSpec.internalBinaryRead(reader, reader.uint32(), options, message.spec);
                    break;
                case /* bool force_rehash */ 4:
                    message.forceRehash = reader.bool();
                    break;
                case /* yatm.job_storage.PreviewPolicy preview_policy */ 6:
                    message.previewPolicy = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateArchiveJobRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 priority = 1; */
        if (message.priority !== 0n)
            writer.tag(1, WireType.Varint).int64(message.priority);
        /* yatm.job_storage.ArchiveJobSpec spec = 2; */
        if (message.spec)
            ArchiveJobSpec.internalBinaryWrite(message.spec, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* bool force_rehash = 4; */
        if (message.forceRehash !== false)
            writer.tag(4, WireType.Varint).bool(message.forceRehash);
        /* yatm.job_storage.PreviewPolicy preview_policy = 6; */
        if (message.previewPolicy !== 0)
            writer.tag(6, WireType.Varint).int32(message.previewPolicy);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message job_archive.CreateArchiveJobRequest
 */
export const CreateArchiveJobRequest = new CreateArchiveJobRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateArchiveJobReply$Type extends MessageType<CreateArchiveJobReply> {
    constructor() {
        super("job_archive.CreateArchiveJobReply", [
            { no: 1, name: "job", kind: "message", T: () => Job }
        ]);
    }
    create(value?: PartialMessage<CreateArchiveJobReply>): CreateArchiveJobReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateArchiveJobReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateArchiveJobReply): CreateArchiveJobReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* job.Job job */ 1:
                    message.job = Job.internalBinaryRead(reader, reader.uint32(), options, message.job);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateArchiveJobReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* job.Job job = 1; */
        if (message.job)
            Job.internalBinaryWrite(message.job, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message job_archive.CreateArchiveJobReply
 */
export const CreateArchiveJobReply = new CreateArchiveJobReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WriteArchiveMediaRequest$Type extends MessageType<WriteArchiveMediaRequest> {
    constructor() {
        super("job_archive.WriteArchiveMediaRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "target", kind: "message", T: () => ArchiveMediaTarget }
        ]);
    }
    create(value?: PartialMessage<WriteArchiveMediaRequest>): WriteArchiveMediaRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<WriteArchiveMediaRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WriteArchiveMediaRequest): WriteArchiveMediaRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* media.ArchiveMediaTarget target */ 2:
                    message.target = ArchiveMediaTarget.internalBinaryRead(reader, reader.uint32(), options, message.target);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WriteArchiveMediaRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* media.ArchiveMediaTarget target = 2; */
        if (message.target)
            ArchiveMediaTarget.internalBinaryWrite(message.target, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message job_archive.WriteArchiveMediaRequest
 */
export const WriteArchiveMediaRequest = new WriteArchiveMediaRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WriteArchiveMediaReply$Type extends MessageType<WriteArchiveMediaReply> {
    constructor() {
        super("job_archive.WriteArchiveMediaReply", []);
    }
    create(value?: PartialMessage<WriteArchiveMediaReply>): WriteArchiveMediaReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<WriteArchiveMediaReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WriteArchiveMediaReply): WriteArchiveMediaReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WriteArchiveMediaReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message job_archive.WriteArchiveMediaReply
 */
export const WriteArchiveMediaReply = new WriteArchiveMediaReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetArchiveJobProgressRequest$Type extends MessageType<GetArchiveJobProgressRequest> {
    constructor() {
        super("job_archive.GetArchiveJobProgressRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<GetArchiveJobProgressRequest>): GetArchiveJobProgressRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<GetArchiveJobProgressRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetArchiveJobProgressRequest): GetArchiveJobProgressRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetArchiveJobProgressRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message job_archive.GetArchiveJobProgressRequest
 */
export const GetArchiveJobProgressRequest = new GetArchiveJobProgressRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetArchiveJobProgressReply$Type extends MessageType<GetArchiveJobProgressReply> {
    constructor() {
        super("job_archive.GetArchiveJobProgressReply", [
            { no: 1, name: "progress", kind: "message", T: () => Progress },
            { no: 2, name: "preview_job_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "preview_error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetArchiveJobProgressReply>): GetArchiveJobProgressReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.previewJobId = 0n;
        message.previewError = "";
        if (value !== undefined)
            reflectionMergePartial<GetArchiveJobProgressReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetArchiveJobProgressReply): GetArchiveJobProgressReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* progress.Progress progress */ 1:
                    message.progress = Progress.internalBinaryRead(reader, reader.uint32(), options, message.progress);
                    break;
                case /* int64 preview_job_id */ 2:
                    message.previewJobId = reader.int64().toBigInt();
                    break;
                case /* string preview_error */ 3:
                    message.previewError = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetArchiveJobProgressReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* progress.Progress progress = 1; */
        if (message.progress)
            Progress.internalBinaryWrite(message.progress, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int64 preview_job_id = 2; */
        if (message.previewJobId !== 0n)
            writer.tag(2, WireType.Varint).int64(message.previewJobId);
        /* string preview_error = 3; */
        if (message.previewError !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.previewError);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message job_archive.GetArchiveJobProgressReply
 */
export const GetArchiveJobProgressReply = new GetArchiveJobProgressReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListArchiveJobFilesRequest$Type extends MessageType<ListArchiveJobFilesRequest> {
    constructor() {
        super("job_archive.ListArchiveJobFilesRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "offset", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "filter_status", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["copy_status.CopyStatus", CopyStatus] }
        ]);
    }
    create(value?: PartialMessage<ListArchiveJobFilesRequest>): ListArchiveJobFilesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.limit = 0;
        message.filterStatus = [];
        if (value !== undefined)
            reflectionMergePartial<ListArchiveJobFilesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListArchiveJobFilesRequest): ListArchiveJobFilesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* int32 limit */ 2:
                    message.limit = reader.int32();
                    break;
                case /* optional int64 offset */ 3:
                    message.offset = reader.int64().toBigInt();
                    break;
                case /* repeated copy_status.CopyStatus filter_status */ 4:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.filterStatus.push(reader.int32());
                    else
                        message.filterStatus.push(reader.int32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListArchiveJobFilesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* int32 limit = 2; */
        if (message.limit !== 0)
            writer.tag(2, WireType.Varint).int32(message.limit);
        /* optional int64 offset = 3; */
        if (message.offset !== undefined)
            writer.tag(3, WireType.Varint).int64(message.offset);
        /* repeated copy_status.CopyStatus filter_status = 4; */
        if (message.filterStatus.length) {
            writer.tag(4, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.filterStatus.length; i++)
                writer.int32(message.filterStatus[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message job_archive.ListArchiveJobFilesRequest
 */
export const ListArchiveJobFilesRequest = new ListArchiveJobFilesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListArchiveJobFilesReply$Type extends MessageType<ListArchiveJobFilesReply> {
    constructor() {
        super("job_archive.ListArchiveJobFilesReply", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ArchiveItem }
        ]);
    }
    create(value?: PartialMessage<ListArchiveJobFilesReply>): ListArchiveJobFilesReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<ListArchiveJobFilesReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListArchiveJobFilesReply): ListArchiveJobFilesReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated job_archive.ArchiveItem items */ 1:
                    message.items.push(ArchiveItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListArchiveJobFilesReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated job_archive.ArchiveItem items = 1; */
        for (let i = 0; i < message.items.length; i++)
            ArchiveItem.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message job_archive.ListArchiveJobFilesReply
 */
export const ListArchiveJobFilesReply = new ListArchiveJobFilesReply$Type();
/**
 * @generated ServiceType for protobuf service job_archive.ArchiveJobService
 */
export const ArchiveJobService = new ServiceType("job_archive.ArchiveJobService", [
    { name: "Create", options: {}, I: CreateArchiveJobRequest, O: CreateArchiveJobReply },
    { name: "WriteMedia", options: {}, I: WriteArchiveMediaRequest, O: WriteArchiveMediaReply },
    { name: "GetProgress", options: {}, I: GetArchiveJobProgressRequest, O: GetArchiveJobProgressReply },
    { name: "ListFiles", options: {}, I: ListArchiveJobFilesRequest, O: ListArchiveJobFilesReply }
]);
