// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "library_entity_type.proto" (package "library_entity_type", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum library_entity_type.LibraryEntityType
 */
export enum LibraryEntityType {
    /**
     * @generated from protobuf enum value: NONE = 0;
     */
    NONE = 0,
    /**
     * @generated from protobuf enum value: FILE = 1;
     */
    FILE = 1,
    /**
     * @generated from protobuf enum value: MEDIA = 2;
     */
    MEDIA = 2,
    /**
     * @generated from protobuf enum value: POSITION = 3;
     */
    POSITION = 3,
    /**
     * @generated from protobuf enum value: LOCATION = 4;
     */
    LOCATION = 4,
    /**
     * @generated from protobuf enum value: FILE_LOCATION = 5;
     */
    FILE_LOCATION = 5,
    /**
     * @generated from protobuf enum value: FILE_VERSION = 6;
     */
    FILE_VERSION = 6,
    /**
     * @generated from protobuf enum value: FILE_TRACKING_KEY = 7;
     */
    FILE_TRACKING_KEY = 7,
    /**
     * @generated from protobuf enum value: RESTORE_RESULT = 8;
     */
    RESTORE_RESULT = 8
}
