// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "library_service.proto" (package "yatm.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { LibraryService } from "./library_service";
import type { TrimLibraryResponse } from "./library_service";
import type { TrimLibraryRequest } from "./library_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListTagsResponse } from "./library_service";
import type { ListTagsRequest } from "./library_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service yatm.v1.LibraryService
 */
export interface ILibraryServiceClient {
    /**
     * @generated from protobuf rpc: ListTags
     */
    listTags(input: ListTagsRequest, options?: RpcOptions): UnaryCall<ListTagsRequest, ListTagsResponse>;
    /**
     * @generated from protobuf rpc: Trim
     */
    trim(input: TrimLibraryRequest, options?: RpcOptions): UnaryCall<TrimLibraryRequest, TrimLibraryResponse>;
}
/**
 * @generated from protobuf service yatm.v1.LibraryService
 */
export class LibraryServiceClient implements ILibraryServiceClient, ServiceInfo {
    typeName = LibraryService.typeName;
    methods = LibraryService.methods;
    options = LibraryService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListTags
     */
    listTags(input: ListTagsRequest, options?: RpcOptions): UnaryCall<ListTagsRequest, ListTagsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTagsRequest, ListTagsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Trim
     */
    trim(input: TrimLibraryRequest, options?: RpcOptions): UnaryCall<TrimLibraryRequest, TrimLibraryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<TrimLibraryRequest, TrimLibraryResponse>("unary", this._transport, method, opt, input);
    }
}
