// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "preview.proto" (package "yatm.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message yatm.v1.GetPreviewCapabilitiesRequest
 */
export interface GetPreviewCapabilitiesRequest {
}
/**
 * @generated from protobuf message yatm.v1.PreviewInputFormats
 */
export interface PreviewInputFormats {
    /**
     * @generated from protobuf field: repeated string extensions = 1
     */
    extensions: string[];
}
/**
 * @generated from protobuf message yatm.v1.GetPreviewCapabilitiesResponse
 */
export interface GetPreviewCapabilitiesResponse {
    /**
     * @generated from protobuf field: bool available = 1
     */
    available: boolean;
    /**
     * @generated from protobuf field: string reason = 2
     */
    reason: string;
    /**
     * @generated from protobuf field: string version = 3
     */
    version: string;
    /**
     * @generated from protobuf field: string ffmpeg_version = 4
     */
    ffmpegVersion: string;
    /**
     * @generated from protobuf field: repeated string kinds = 5
     */
    kinds: string[];
    /**
     * @generated from protobuf field: repeated string input_extensions = 6
     */
    inputExtensions: string[];
    /**
     * @generated from protobuf field: repeated string output_formats = 7
     */
    outputFormats: string[];
    /**
     * @generated from protobuf field: map<string, yatm.v1.PreviewInputFormats> input_extensions_by_kind = 8
     */
    inputExtensionsByKind: {
        [key: string]: PreviewInputFormats;
    };
    /**
     * @generated from protobuf field: string libraw_version = 9
     */
    librawVersion: string;
}
/**
 * @generated from protobuf message yatm.v1.GetPreviewRequest
 */
export interface GetPreviewRequest {
    /**
     * Preview storage is content-addressed, so the request names the content itself: a caller
     * resolves a File, version or recorded Position to its signature before asking.
     *
     * @generated from protobuf field: bytes signature = 1
     */
    signature: Uint8Array;
}
/**
 * @generated from protobuf message yatm.v1.PreviewResource
 */
export interface PreviewResource {
    /**
     * @generated from protobuf field: string role = 1
     */
    role: string;
    /**
     * @generated from protobuf field: string media_type = 2
     */
    mediaType: string;
    /**
     * @generated from protobuf field: uint32 width_px = 3
     */
    widthPx: number;
    /**
     * @generated from protobuf field: uint32 height_px = 4
     */
    heightPx: number;
    /**
     * @generated from protobuf field: string url = 5
     */
    url: string;
}
/**
 * @generated from protobuf message yatm.v1.GetPreviewResponse
 */
export interface GetPreviewResponse {
    /**
     * @generated from protobuf field: yatm.v1.PreviewAvailability availability = 1
     */
    availability: PreviewAvailability;
    /**
     * @generated from protobuf field: repeated yatm.v1.PreviewResource assets = 2
     */
    assets: PreviewResource[];
}
/**
 * @generated from protobuf message yatm.v1.PreviewManifest
 */
export interface PreviewManifest {
    /**
     * @generated from protobuf field: bytes file_signature = 1
     */
    fileSignature: Uint8Array;
    /**
     * @generated from protobuf field: string generator = 2
     */
    generator: string;
    /**
     * @generated from protobuf field: bytes settings_json = 3
     */
    settingsJson: Uint8Array;
    /**
     * @generated from protobuf field: repeated yatm.v1.PreviewAsset assets = 4
     */
    assets: PreviewAsset[];
}
/**
 * @generated from protobuf message yatm.v1.PreviewAsset
 */
export interface PreviewAsset {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string role = 2
     */
    role: string;
    /**
     * @generated from protobuf field: string media_type = 3
     */
    mediaType: string;
    /**
     * @generated from protobuf field: uint32 width_px = 4
     */
    widthPx: number;
    /**
     * @generated from protobuf field: uint32 height_px = 5
     */
    heightPx: number;
}
/**
 * @generated from protobuf enum yatm.v1.PreviewAvailability
 */
export enum PreviewAvailability {
    /**
     * @generated from protobuf enum value: PREVIEW_AVAILABILITY_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: PREVIEW_AVAILABILITY_READY = 1;
     */
    READY = 1,
    /**
     * @generated from protobuf enum value: PREVIEW_AVAILABILITY_NOT_GENERATED = 2;
     */
    NOT_GENERATED = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class GetPreviewCapabilitiesRequest$Type extends MessageType<GetPreviewCapabilitiesRequest> {
    constructor() {
        super("yatm.v1.GetPreviewCapabilitiesRequest", []);
    }
    create(value?: PartialMessage<GetPreviewCapabilitiesRequest>): GetPreviewCapabilitiesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetPreviewCapabilitiesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPreviewCapabilitiesRequest): GetPreviewCapabilitiesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPreviewCapabilitiesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.GetPreviewCapabilitiesRequest
 */
export const GetPreviewCapabilitiesRequest = new GetPreviewCapabilitiesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PreviewInputFormats$Type extends MessageType<PreviewInputFormats> {
    constructor() {
        super("yatm.v1.PreviewInputFormats", [
            { no: 1, name: "extensions", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PreviewInputFormats>): PreviewInputFormats {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.extensions = [];
        if (value !== undefined)
            reflectionMergePartial<PreviewInputFormats>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PreviewInputFormats): PreviewInputFormats {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string extensions */ 1:
                    message.extensions.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PreviewInputFormats, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string extensions = 1; */
        for (let i = 0; i < message.extensions.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.extensions[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.PreviewInputFormats
 */
export const PreviewInputFormats = new PreviewInputFormats$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPreviewCapabilitiesResponse$Type extends MessageType<GetPreviewCapabilitiesResponse> {
    constructor() {
        super("yatm.v1.GetPreviewCapabilitiesResponse", [
            { no: 1, name: "available", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "ffmpeg_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "kinds", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "input_extensions", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "output_formats", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "input_extensions_by_kind", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "message", T: () => PreviewInputFormats } },
            { no: 9, name: "libraw_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetPreviewCapabilitiesResponse>): GetPreviewCapabilitiesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.available = false;
        message.reason = "";
        message.version = "";
        message.ffmpegVersion = "";
        message.kinds = [];
        message.inputExtensions = [];
        message.outputFormats = [];
        message.inputExtensionsByKind = {};
        message.librawVersion = "";
        if (value !== undefined)
            reflectionMergePartial<GetPreviewCapabilitiesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPreviewCapabilitiesResponse): GetPreviewCapabilitiesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool available */ 1:
                    message.available = reader.bool();
                    break;
                case /* string reason */ 2:
                    message.reason = reader.string();
                    break;
                case /* string version */ 3:
                    message.version = reader.string();
                    break;
                case /* string ffmpeg_version */ 4:
                    message.ffmpegVersion = reader.string();
                    break;
                case /* repeated string kinds */ 5:
                    message.kinds.push(reader.string());
                    break;
                case /* repeated string input_extensions */ 6:
                    message.inputExtensions.push(reader.string());
                    break;
                case /* repeated string output_formats */ 7:
                    message.outputFormats.push(reader.string());
                    break;
                case /* map<string, yatm.v1.PreviewInputFormats> input_extensions_by_kind */ 8:
                    this.binaryReadMap8(message.inputExtensionsByKind, reader, options);
                    break;
                case /* string libraw_version */ 9:
                    message.librawVersion = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap8(map: GetPreviewCapabilitiesResponse["inputExtensionsByKind"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof GetPreviewCapabilitiesResponse["inputExtensionsByKind"] | undefined, val: GetPreviewCapabilitiesResponse["inputExtensionsByKind"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = PreviewInputFormats.internalBinaryRead(reader, reader.uint32(), options);
                    break;
                default: throw new globalThis.Error("unknown map entry field for yatm.v1.GetPreviewCapabilitiesResponse.input_extensions_by_kind");
            }
        }
        map[key ?? ""] = val ?? PreviewInputFormats.create();
    }
    internalBinaryWrite(message: GetPreviewCapabilitiesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool available = 1; */
        if (message.available !== false)
            writer.tag(1, WireType.Varint).bool(message.available);
        /* string reason = 2; */
        if (message.reason !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.reason);
        /* string version = 3; */
        if (message.version !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.version);
        /* string ffmpeg_version = 4; */
        if (message.ffmpegVersion !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.ffmpegVersion);
        /* repeated string kinds = 5; */
        for (let i = 0; i < message.kinds.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.kinds[i]);
        /* repeated string input_extensions = 6; */
        for (let i = 0; i < message.inputExtensions.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.inputExtensions[i]);
        /* repeated string output_formats = 7; */
        for (let i = 0; i < message.outputFormats.length; i++)
            writer.tag(7, WireType.LengthDelimited).string(message.outputFormats[i]);
        /* map<string, yatm.v1.PreviewInputFormats> input_extensions_by_kind = 8; */
        for (let k of globalThis.Object.keys(message.inputExtensionsByKind)) {
            writer.tag(8, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k);
            writer.tag(2, WireType.LengthDelimited).fork();
            PreviewInputFormats.internalBinaryWrite(message.inputExtensionsByKind[k], writer, options);
            writer.join().join();
        }
        /* string libraw_version = 9; */
        if (message.librawVersion !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.librawVersion);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.GetPreviewCapabilitiesResponse
 */
export const GetPreviewCapabilitiesResponse = new GetPreviewCapabilitiesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPreviewRequest$Type extends MessageType<GetPreviewRequest> {
    constructor() {
        super("yatm.v1.GetPreviewRequest", [
            { no: 1, name: "signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<GetPreviewRequest>): GetPreviewRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.signature = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<GetPreviewRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPreviewRequest): GetPreviewRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes signature */ 1:
                    message.signature = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPreviewRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes signature = 1; */
        if (message.signature.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.signature);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.GetPreviewRequest
 */
export const GetPreviewRequest = new GetPreviewRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PreviewResource$Type extends MessageType<PreviewResource> {
    constructor() {
        super("yatm.v1.PreviewResource", [
            { no: 1, name: "role", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "media_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "width_px", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "height_px", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PreviewResource>): PreviewResource {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.role = "";
        message.mediaType = "";
        message.widthPx = 0;
        message.heightPx = 0;
        message.url = "";
        if (value !== undefined)
            reflectionMergePartial<PreviewResource>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PreviewResource): PreviewResource {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string role */ 1:
                    message.role = reader.string();
                    break;
                case /* string media_type */ 2:
                    message.mediaType = reader.string();
                    break;
                case /* uint32 width_px */ 3:
                    message.widthPx = reader.uint32();
                    break;
                case /* uint32 height_px */ 4:
                    message.heightPx = reader.uint32();
                    break;
                case /* string url */ 5:
                    message.url = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PreviewResource, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string role = 1; */
        if (message.role !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.role);
        /* string media_type = 2; */
        if (message.mediaType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.mediaType);
        /* uint32 width_px = 3; */
        if (message.widthPx !== 0)
            writer.tag(3, WireType.Varint).uint32(message.widthPx);
        /* uint32 height_px = 4; */
        if (message.heightPx !== 0)
            writer.tag(4, WireType.Varint).uint32(message.heightPx);
        /* string url = 5; */
        if (message.url !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.url);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.PreviewResource
 */
export const PreviewResource = new PreviewResource$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPreviewResponse$Type extends MessageType<GetPreviewResponse> {
    constructor() {
        super("yatm.v1.GetPreviewResponse", [
            { no: 1, name: "availability", kind: "enum", T: () => ["yatm.v1.PreviewAvailability", PreviewAvailability, "PREVIEW_AVAILABILITY_"] },
            { no: 2, name: "assets", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PreviewResource }
        ]);
    }
    create(value?: PartialMessage<GetPreviewResponse>): GetPreviewResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.availability = 0;
        message.assets = [];
        if (value !== undefined)
            reflectionMergePartial<GetPreviewResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPreviewResponse): GetPreviewResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* yatm.v1.PreviewAvailability availability */ 1:
                    message.availability = reader.int32();
                    break;
                case /* repeated yatm.v1.PreviewResource assets */ 2:
                    message.assets.push(PreviewResource.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPreviewResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* yatm.v1.PreviewAvailability availability = 1; */
        if (message.availability !== 0)
            writer.tag(1, WireType.Varint).int32(message.availability);
        /* repeated yatm.v1.PreviewResource assets = 2; */
        for (let i = 0; i < message.assets.length; i++)
            PreviewResource.internalBinaryWrite(message.assets[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.GetPreviewResponse
 */
export const GetPreviewResponse = new GetPreviewResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PreviewManifest$Type extends MessageType<PreviewManifest> {
    constructor() {
        super("yatm.v1.PreviewManifest", [
            { no: 1, name: "file_signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "generator", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "settings_json", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 4, name: "assets", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PreviewAsset }
        ]);
    }
    create(value?: PartialMessage<PreviewManifest>): PreviewManifest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fileSignature = new Uint8Array(0);
        message.generator = "";
        message.settingsJson = new Uint8Array(0);
        message.assets = [];
        if (value !== undefined)
            reflectionMergePartial<PreviewManifest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PreviewManifest): PreviewManifest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes file_signature */ 1:
                    message.fileSignature = reader.bytes();
                    break;
                case /* string generator */ 2:
                    message.generator = reader.string();
                    break;
                case /* bytes settings_json */ 3:
                    message.settingsJson = reader.bytes();
                    break;
                case /* repeated yatm.v1.PreviewAsset assets */ 4:
                    message.assets.push(PreviewAsset.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PreviewManifest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes file_signature = 1; */
        if (message.fileSignature.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.fileSignature);
        /* string generator = 2; */
        if (message.generator !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.generator);
        /* bytes settings_json = 3; */
        if (message.settingsJson.length)
            writer.tag(3, WireType.LengthDelimited).bytes(message.settingsJson);
        /* repeated yatm.v1.PreviewAsset assets = 4; */
        for (let i = 0; i < message.assets.length; i++)
            PreviewAsset.internalBinaryWrite(message.assets[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.PreviewManifest
 */
export const PreviewManifest = new PreviewManifest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PreviewAsset$Type extends MessageType<PreviewAsset> {
    constructor() {
        super("yatm.v1.PreviewAsset", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "role", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "media_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "width_px", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "height_px", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<PreviewAsset>): PreviewAsset {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.role = "";
        message.mediaType = "";
        message.widthPx = 0;
        message.heightPx = 0;
        if (value !== undefined)
            reflectionMergePartial<PreviewAsset>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PreviewAsset): PreviewAsset {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string role */ 2:
                    message.role = reader.string();
                    break;
                case /* string media_type */ 3:
                    message.mediaType = reader.string();
                    break;
                case /* uint32 width_px */ 4:
                    message.widthPx = reader.uint32();
                    break;
                case /* uint32 height_px */ 5:
                    message.heightPx = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PreviewAsset, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string role = 2; */
        if (message.role !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.role);
        /* string media_type = 3; */
        if (message.mediaType !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.mediaType);
        /* uint32 width_px = 4; */
        if (message.widthPx !== 0)
            writer.tag(4, WireType.Varint).uint32(message.widthPx);
        /* uint32 height_px = 5; */
        if (message.heightPx !== 0)
            writer.tag(5, WireType.Varint).uint32(message.heightPx);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.PreviewAsset
 */
export const PreviewAsset = new PreviewAsset$Type();
/**
 * @generated ServiceType for protobuf service yatm.v1.PreviewService
 */
export const PreviewService = new ServiceType("yatm.v1.PreviewService", [
    { name: "Get", options: {}, I: GetPreviewRequest, O: GetPreviewResponse },
    { name: "GetCapabilities", options: {}, I: GetPreviewCapabilitiesRequest, O: GetPreviewCapabilitiesResponse }
]);
