// @generated by protobuf-ts 2.8.2
// @generated from protobuf file "service.proto" (package "service", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Service } from "./service";
import type { DeviceListReply } from "./service";
import type { DeviceListRequest } from "./service";
import type { SourceListReply } from "./service";
import type { SourceListRequest } from "./service";
import type { JobGetLogReply } from "./service";
import type { JobGetLogRequest } from "./service";
import type { JobDisplayReply } from "./service";
import type { JobDisplayRequest } from "./service";
import type { JobNextReply } from "./service";
import type { JobNextRequest } from "./service";
import type { JobCreateReply } from "./service";
import type { JobCreateRequest } from "./service";
import type { JobListReply } from "./service";
import type { JobListRequest } from "./service";
import type { TapeMGetReply } from "./service";
import type { TapeMGetRequest } from "./service";
import type { FileListParentsReply } from "./service";
import type { FileListParentsRequest } from "./service";
import type { FileDeleteReply } from "./service";
import type { FileDeleteRequest } from "./service";
import type { FileMkdirReply } from "./service";
import type { FileMkdirRequest } from "./service";
import type { FileEditReply } from "./service";
import type { FileEditRequest } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { FileGetReply } from "./service";
import type { FileGetRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service service.Service
 */
export interface IServiceClient {
    /**
     * @generated from protobuf rpc: FileGet(service.FileGetRequest) returns (service.FileGetReply);
     */
    fileGet(input: FileGetRequest, options?: RpcOptions): UnaryCall<FileGetRequest, FileGetReply>;
    /**
     * @generated from protobuf rpc: FileEdit(service.FileEditRequest) returns (service.FileEditReply);
     */
    fileEdit(input: FileEditRequest, options?: RpcOptions): UnaryCall<FileEditRequest, FileEditReply>;
    /**
     * @generated from protobuf rpc: FileMkdir(service.FileMkdirRequest) returns (service.FileMkdirReply);
     */
    fileMkdir(input: FileMkdirRequest, options?: RpcOptions): UnaryCall<FileMkdirRequest, FileMkdirReply>;
    /**
     * @generated from protobuf rpc: FileDelete(service.FileDeleteRequest) returns (service.FileDeleteReply);
     */
    fileDelete(input: FileDeleteRequest, options?: RpcOptions): UnaryCall<FileDeleteRequest, FileDeleteReply>;
    /**
     * @generated from protobuf rpc: FileListParents(service.FileListParentsRequest) returns (service.FileListParentsReply);
     */
    fileListParents(input: FileListParentsRequest, options?: RpcOptions): UnaryCall<FileListParentsRequest, FileListParentsReply>;
    /**
     * @generated from protobuf rpc: TapeMGet(service.TapeMGetRequest) returns (service.TapeMGetReply);
     */
    tapeMGet(input: TapeMGetRequest, options?: RpcOptions): UnaryCall<TapeMGetRequest, TapeMGetReply>;
    /**
     * @generated from protobuf rpc: JobList(service.JobListRequest) returns (service.JobListReply);
     */
    jobList(input: JobListRequest, options?: RpcOptions): UnaryCall<JobListRequest, JobListReply>;
    /**
     * @generated from protobuf rpc: JobCreate(service.JobCreateRequest) returns (service.JobCreateReply);
     */
    jobCreate(input: JobCreateRequest, options?: RpcOptions): UnaryCall<JobCreateRequest, JobCreateReply>;
    /**
     * @generated from protobuf rpc: JobNext(service.JobNextRequest) returns (service.JobNextReply);
     */
    jobNext(input: JobNextRequest, options?: RpcOptions): UnaryCall<JobNextRequest, JobNextReply>;
    /**
     * @generated from protobuf rpc: JobDisplay(service.JobDisplayRequest) returns (service.JobDisplayReply);
     */
    jobDisplay(input: JobDisplayRequest, options?: RpcOptions): UnaryCall<JobDisplayRequest, JobDisplayReply>;
    /**
     * @generated from protobuf rpc: JobGetLog(service.JobGetLogRequest) returns (service.JobGetLogReply);
     */
    jobGetLog(input: JobGetLogRequest, options?: RpcOptions): UnaryCall<JobGetLogRequest, JobGetLogReply>;
    /**
     * @generated from protobuf rpc: SourceList(service.SourceListRequest) returns (service.SourceListReply);
     */
    sourceList(input: SourceListRequest, options?: RpcOptions): UnaryCall<SourceListRequest, SourceListReply>;
    /**
     * @generated from protobuf rpc: DeviceList(service.DeviceListRequest) returns (service.DeviceListReply);
     */
    deviceList(input: DeviceListRequest, options?: RpcOptions): UnaryCall<DeviceListRequest, DeviceListReply>;
}
/**
 * @generated from protobuf service service.Service
 */
export class ServiceClient implements IServiceClient, ServiceInfo {
    typeName = Service.typeName;
    methods = Service.methods;
    options = Service.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: FileGet(service.FileGetRequest) returns (service.FileGetReply);
     */
    fileGet(input: FileGetRequest, options?: RpcOptions): UnaryCall<FileGetRequest, FileGetReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<FileGetRequest, FileGetReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FileEdit(service.FileEditRequest) returns (service.FileEditReply);
     */
    fileEdit(input: FileEditRequest, options?: RpcOptions): UnaryCall<FileEditRequest, FileEditReply> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<FileEditRequest, FileEditReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FileMkdir(service.FileMkdirRequest) returns (service.FileMkdirReply);
     */
    fileMkdir(input: FileMkdirRequest, options?: RpcOptions): UnaryCall<FileMkdirRequest, FileMkdirReply> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<FileMkdirRequest, FileMkdirReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FileDelete(service.FileDeleteRequest) returns (service.FileDeleteReply);
     */
    fileDelete(input: FileDeleteRequest, options?: RpcOptions): UnaryCall<FileDeleteRequest, FileDeleteReply> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<FileDeleteRequest, FileDeleteReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FileListParents(service.FileListParentsRequest) returns (service.FileListParentsReply);
     */
    fileListParents(input: FileListParentsRequest, options?: RpcOptions): UnaryCall<FileListParentsRequest, FileListParentsReply> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<FileListParentsRequest, FileListParentsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: TapeMGet(service.TapeMGetRequest) returns (service.TapeMGetReply);
     */
    tapeMGet(input: TapeMGetRequest, options?: RpcOptions): UnaryCall<TapeMGetRequest, TapeMGetReply> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<TapeMGetRequest, TapeMGetReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: JobList(service.JobListRequest) returns (service.JobListReply);
     */
    jobList(input: JobListRequest, options?: RpcOptions): UnaryCall<JobListRequest, JobListReply> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<JobListRequest, JobListReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: JobCreate(service.JobCreateRequest) returns (service.JobCreateReply);
     */
    jobCreate(input: JobCreateRequest, options?: RpcOptions): UnaryCall<JobCreateRequest, JobCreateReply> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<JobCreateRequest, JobCreateReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: JobNext(service.JobNextRequest) returns (service.JobNextReply);
     */
    jobNext(input: JobNextRequest, options?: RpcOptions): UnaryCall<JobNextRequest, JobNextReply> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<JobNextRequest, JobNextReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: JobDisplay(service.JobDisplayRequest) returns (service.JobDisplayReply);
     */
    jobDisplay(input: JobDisplayRequest, options?: RpcOptions): UnaryCall<JobDisplayRequest, JobDisplayReply> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<JobDisplayRequest, JobDisplayReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: JobGetLog(service.JobGetLogRequest) returns (service.JobGetLogReply);
     */
    jobGetLog(input: JobGetLogRequest, options?: RpcOptions): UnaryCall<JobGetLogRequest, JobGetLogReply> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<JobGetLogRequest, JobGetLogReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SourceList(service.SourceListRequest) returns (service.SourceListReply);
     */
    sourceList(input: SourceListRequest, options?: RpcOptions): UnaryCall<SourceListRequest, SourceListReply> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<SourceListRequest, SourceListReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeviceList(service.DeviceListRequest) returns (service.DeviceListReply);
     */
    deviceList(input: DeviceListRequest, options?: RpcOptions): UnaryCall<DeviceListRequest, DeviceListReply> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeviceListRequest, DeviceListReply>("unary", this._transport, method, opt, input);
    }
}
