// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "settings.proto" (package "settings", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { SettingsService } from "./settings";
import type { BrowsePathsReply } from "./settings";
import type { BrowsePathsRequest } from "./settings";
import type { GetAccessReply } from "./settings";
import type { GetAccessRequest } from "./settings";
import type { UpdateLibrarySettingsReply } from "./settings";
import type { UpdateLibrarySettingsRequest } from "./settings";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { LibrarySettings } from "./settings";
import type { GetLibrarySettingsRequest } from "./settings";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service settings.SettingsService
 */
export interface ISettingsServiceClient {
    /**
     * @generated from protobuf rpc: GetLibrary
     */
    getLibrary(input: GetLibrarySettingsRequest, options?: RpcOptions): UnaryCall<GetLibrarySettingsRequest, LibrarySettings>;
    /**
     * @generated from protobuf rpc: UpdateLibrary
     */
    updateLibrary(input: UpdateLibrarySettingsRequest, options?: RpcOptions): UnaryCall<UpdateLibrarySettingsRequest, UpdateLibrarySettingsReply>;
    /**
     * @generated from protobuf rpc: GetAccess
     */
    getAccess(input: GetAccessRequest, options?: RpcOptions): UnaryCall<GetAccessRequest, GetAccessReply>;
    /**
     * @generated from protobuf rpc: BrowsePaths
     */
    browsePaths(input: BrowsePathsRequest, options?: RpcOptions): UnaryCall<BrowsePathsRequest, BrowsePathsReply>;
}
/**
 * @generated from protobuf service settings.SettingsService
 */
export class SettingsServiceClient implements ISettingsServiceClient, ServiceInfo {
    typeName = SettingsService.typeName;
    methods = SettingsService.methods;
    options = SettingsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetLibrary
     */
    getLibrary(input: GetLibrarySettingsRequest, options?: RpcOptions): UnaryCall<GetLibrarySettingsRequest, LibrarySettings> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetLibrarySettingsRequest, LibrarySettings>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateLibrary
     */
    updateLibrary(input: UpdateLibrarySettingsRequest, options?: RpcOptions): UnaryCall<UpdateLibrarySettingsRequest, UpdateLibrarySettingsReply> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateLibrarySettingsRequest, UpdateLibrarySettingsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAccess
     */
    getAccess(input: GetAccessRequest, options?: RpcOptions): UnaryCall<GetAccessRequest, GetAccessReply> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAccessRequest, GetAccessReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: BrowsePaths
     */
    browsePaths(input: BrowsePathsRequest, options?: RpcOptions): UnaryCall<BrowsePathsRequest, BrowsePathsReply> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<BrowsePathsRequest, BrowsePathsReply>("unary", this._transport, method, opt, input);
    }
}
