// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "settings.proto" (package "yatm.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Library preferences: what the Library shows and how it confirms removal.
 *
 * @generated from protobuf message yatm.v1.LibrarySettings
 */
export interface LibrarySettings {
    /**
     * @generated from protobuf field: bool include_unbacked_files = 1
     */
    includeUnbackedFiles: boolean;
    /**
     * @generated from protobuf field: bool confirm_remove = 2
     */
    confirmRemove: boolean;
}
/**
 * Executor preferences: how an attempt drives the pipeline its runner owns.
 *
 * @generated from protobuf message yatm.v1.JobSettings
 */
export interface JobSettings {
    /**
     * @generated from protobuf field: yatm.v1.JobExecutionSettings execution = 1
     */
    execution?: JobExecutionSettings;
}
/**
 * Job pipeline batching, buffering and delivery cadence. Every limit is an ACP option: the read
 * batch is the manifest page, and the read buffer, the result queue, the result batch and the
 * flush interval are the engine's, so the result writer of an attempt only persists the batches
 * ACP hands over.
 *
 * @generated from protobuf message yatm.v1.JobExecutionSettings
 */
export interface JobExecutionSettings {
    /**
     * @generated from protobuf field: int32 read_batch = 1
     */
    readBatch: number;
    /**
     * @generated from protobuf field: int32 read_buffer_max = 2
     */
    readBufferMax: number;
    /**
     * @generated from protobuf field: int32 write_buffer_max = 3
     */
    writeBufferMax: number;
    /**
     * @generated from protobuf field: int32 write_batch_size = 4
     */
    writeBatchSize: number;
    /**
     * @generated from protobuf field: int32 flush_interval_ms = 5
     */
    flushIntervalMs: number;
}
/**
 * Generation preferences; storage paths remain deployment resources.
 *
 * @generated from protobuf message yatm.v1.PreviewSettings
 */
export interface PreviewSettings {
    /**
     * @generated from protobuf field: repeated yatm.v1.PreviewGeneratorSettings generators = 1
     */
    generators: PreviewGeneratorSettings[];
    /**
     * @generated from protobuf field: bool enabled = 2
     */
    enabled: boolean;
    /**
     * @generated from protobuf field: string command = 3
     */
    command: string;
    /**
     * @generated from protobuf field: int32 concurrency = 4
     */
    concurrency: number;
    /**
     * @generated from protobuf field: int32 timeout_seconds = 5
     */
    timeoutSeconds: number;
    /**
     * @generated from protobuf field: int64 max_input_pixels = 6
     */
    maxInputPixels: bigint;
}
/**
 * The generator routes and output choices frozen when a Job is created. Runtime limits and
 * enablement remain live Settings and are intentionally absent.
 *
 * @generated from protobuf message yatm.v1.PreviewJobSettings
 */
export interface PreviewJobSettings {
    /**
     * @generated from protobuf field: repeated yatm.v1.PreviewGeneratorSettings generators = 1
     */
    generators: PreviewGeneratorSettings[];
}
/**
 * @generated from protobuf message yatm.v1.PreviewExtension
 */
export interface PreviewExtension {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: bool enabled = 2
     */
    enabled: boolean;
}
/**
 * @generated from protobuf message yatm.v1.PreviewGeneratorSettings
 */
export interface PreviewGeneratorSettings {
    /**
     * @generated from protobuf field: bool enabled = 1
     */
    enabled: boolean;
    /**
     * @generated from protobuf field: repeated yatm.v1.PreviewExtension extensions = 2
     */
    extensions: PreviewExtension[];
    /**
     * @generated from protobuf oneof: options
     */
    options: {
        oneofKind: "image";
        /**
         * @generated from protobuf field: yatm.v1.ImagePreviewSettings image = 3
         */
        image: ImagePreviewSettings;
    } | {
        oneofKind: "video";
        /**
         * @generated from protobuf field: yatm.v1.VideoPreviewSettings video = 4
         */
        video: VideoPreviewSettings;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message yatm.v1.ImagePreviewSettings
 */
export interface ImagePreviewSettings {
    /**
     * @generated from protobuf field: int32 max_width = 1
     */
    maxWidth: number;
    /**
     * @generated from protobuf field: int32 max_height = 2
     */
    maxHeight: number;
    /**
     * @generated from protobuf field: string format = 3
     */
    format: string;
    /**
     * @generated from protobuf field: int32 quality = 4
     */
    quality: number;
}
/**
 * @generated from protobuf message yatm.v1.VideoPreviewSettings
 */
export interface VideoPreviewSettings {
    /**
     * @generated from protobuf field: int32 poster_width = 1
     */
    posterWidth: number;
    /**
     * @generated from protobuf field: int32 poster_height = 2
     */
    posterHeight: number;
    /**
     * @generated from protobuf field: int32 timeline_width = 3
     */
    timelineWidth: number;
    /**
     * @generated from protobuf field: int32 timeline_height = 4
     */
    timelineHeight: number;
    /**
     * @generated from protobuf field: int32 timeline_interval_seconds = 5
     */
    timelineIntervalSeconds: number;
    /**
     * @generated from protobuf field: int32 timeline_max_frames = 6
     */
    timelineMaxFrames: number;
    /**
     * @generated from protobuf field: string format = 7
     */
    format: string;
    /**
     * @generated from protobuf field: int32 quality = 8
     */
    quality: number;
}
/**
 * @generated from protobuf message yatm.v1.SettingsValue
 */
export interface SettingsValue {
    /**
     * @generated from protobuf oneof: value
     */
    value: {
        oneofKind: "library";
        /**
         * @generated from protobuf field: yatm.v1.LibrarySettings library = 1
         */
        library: LibrarySettings;
    } | {
        oneofKind: "preview";
        /**
         * @generated from protobuf field: yatm.v1.PreviewSettings preview = 2
         */
        preview: PreviewSettings;
    } | {
        oneofKind: "job";
        /**
         * @generated from protobuf field: yatm.v1.JobSettings job = 3
         */
        job: JobSettings;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message yatm.v1.GetSettingsRequest
 */
export interface GetSettingsRequest {
    /**
     * @generated from protobuf field: yatm.v1.SettingsGroup group = 1
     */
    group: SettingsGroup;
}
/**
 * @generated from protobuf message yatm.v1.GetSettingsResponse
 */
export interface GetSettingsResponse {
    /**
     * @generated from protobuf field: yatm.v1.SettingsValue value = 1
     */
    value?: SettingsValue;
}
/**
 * @generated from protobuf message yatm.v1.UpdateSettingsRequest
 */
export interface UpdateSettingsRequest {
    /**
     * @generated from protobuf field: yatm.v1.SettingsValue value = 1
     */
    value?: SettingsValue;
}
/**
 * @generated from protobuf message yatm.v1.UpdateSettingsResponse
 */
export interface UpdateSettingsResponse {
    /**
     * @generated from protobuf field: yatm.v1.SettingsValue value = 1
     */
    value?: SettingsValue;
}
/**
 * @generated from protobuf enum yatm.v1.SettingsGroup
 */
export enum SettingsGroup {
    /**
     * @generated from protobuf enum value: SETTINGS_GROUP_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: SETTINGS_GROUP_LIBRARY = 1;
     */
    LIBRARY = 1,
    /**
     * @generated from protobuf enum value: SETTINGS_GROUP_PREVIEW = 2;
     */
    PREVIEW = 2,
    /**
     * @generated from protobuf enum value: SETTINGS_GROUP_JOB = 3;
     */
    JOB = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class LibrarySettings$Type extends MessageType<LibrarySettings> {
    constructor() {
        super("yatm.v1.LibrarySettings", [
            { no: 1, name: "include_unbacked_files", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "confirm_remove", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<LibrarySettings>): LibrarySettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.includeUnbackedFiles = false;
        message.confirmRemove = false;
        if (value !== undefined)
            reflectionMergePartial<LibrarySettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LibrarySettings): LibrarySettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool include_unbacked_files */ 1:
                    message.includeUnbackedFiles = reader.bool();
                    break;
                case /* bool confirm_remove */ 2:
                    message.confirmRemove = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LibrarySettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool include_unbacked_files = 1; */
        if (message.includeUnbackedFiles !== false)
            writer.tag(1, WireType.Varint).bool(message.includeUnbackedFiles);
        /* bool confirm_remove = 2; */
        if (message.confirmRemove !== false)
            writer.tag(2, WireType.Varint).bool(message.confirmRemove);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.LibrarySettings
 */
export const LibrarySettings = new LibrarySettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JobSettings$Type extends MessageType<JobSettings> {
    constructor() {
        super("yatm.v1.JobSettings", [
            { no: 1, name: "execution", kind: "message", T: () => JobExecutionSettings }
        ]);
    }
    create(value?: PartialMessage<JobSettings>): JobSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<JobSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JobSettings): JobSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* yatm.v1.JobExecutionSettings execution */ 1:
                    message.execution = JobExecutionSettings.internalBinaryRead(reader, reader.uint32(), options, message.execution);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JobSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* yatm.v1.JobExecutionSettings execution = 1; */
        if (message.execution)
            JobExecutionSettings.internalBinaryWrite(message.execution, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.JobSettings
 */
export const JobSettings = new JobSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JobExecutionSettings$Type extends MessageType<JobExecutionSettings> {
    constructor() {
        super("yatm.v1.JobExecutionSettings", [
            { no: 1, name: "read_batch", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "read_buffer_max", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "write_buffer_max", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "write_batch_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "flush_interval_ms", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<JobExecutionSettings>): JobExecutionSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.readBatch = 0;
        message.readBufferMax = 0;
        message.writeBufferMax = 0;
        message.writeBatchSize = 0;
        message.flushIntervalMs = 0;
        if (value !== undefined)
            reflectionMergePartial<JobExecutionSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JobExecutionSettings): JobExecutionSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 read_batch */ 1:
                    message.readBatch = reader.int32();
                    break;
                case /* int32 read_buffer_max */ 2:
                    message.readBufferMax = reader.int32();
                    break;
                case /* int32 write_buffer_max */ 3:
                    message.writeBufferMax = reader.int32();
                    break;
                case /* int32 write_batch_size */ 4:
                    message.writeBatchSize = reader.int32();
                    break;
                case /* int32 flush_interval_ms */ 5:
                    message.flushIntervalMs = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JobExecutionSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 read_batch = 1; */
        if (message.readBatch !== 0)
            writer.tag(1, WireType.Varint).int32(message.readBatch);
        /* int32 read_buffer_max = 2; */
        if (message.readBufferMax !== 0)
            writer.tag(2, WireType.Varint).int32(message.readBufferMax);
        /* int32 write_buffer_max = 3; */
        if (message.writeBufferMax !== 0)
            writer.tag(3, WireType.Varint).int32(message.writeBufferMax);
        /* int32 write_batch_size = 4; */
        if (message.writeBatchSize !== 0)
            writer.tag(4, WireType.Varint).int32(message.writeBatchSize);
        /* int32 flush_interval_ms = 5; */
        if (message.flushIntervalMs !== 0)
            writer.tag(5, WireType.Varint).int32(message.flushIntervalMs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.JobExecutionSettings
 */
export const JobExecutionSettings = new JobExecutionSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PreviewSettings$Type extends MessageType<PreviewSettings> {
    constructor() {
        super("yatm.v1.PreviewSettings", [
            { no: 1, name: "generators", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PreviewGeneratorSettings },
            { no: 2, name: "enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "command", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "concurrency", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "timeout_seconds", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "max_input_pixels", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<PreviewSettings>): PreviewSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.generators = [];
        message.enabled = false;
        message.command = "";
        message.concurrency = 0;
        message.timeoutSeconds = 0;
        message.maxInputPixels = 0n;
        if (value !== undefined)
            reflectionMergePartial<PreviewSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PreviewSettings): PreviewSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated yatm.v1.PreviewGeneratorSettings generators */ 1:
                    message.generators.push(PreviewGeneratorSettings.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bool enabled */ 2:
                    message.enabled = reader.bool();
                    break;
                case /* string command */ 3:
                    message.command = reader.string();
                    break;
                case /* int32 concurrency */ 4:
                    message.concurrency = reader.int32();
                    break;
                case /* int32 timeout_seconds */ 5:
                    message.timeoutSeconds = reader.int32();
                    break;
                case /* int64 max_input_pixels */ 6:
                    message.maxInputPixels = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PreviewSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated yatm.v1.PreviewGeneratorSettings generators = 1; */
        for (let i = 0; i < message.generators.length; i++)
            PreviewGeneratorSettings.internalBinaryWrite(message.generators[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool enabled = 2; */
        if (message.enabled !== false)
            writer.tag(2, WireType.Varint).bool(message.enabled);
        /* string command = 3; */
        if (message.command !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.command);
        /* int32 concurrency = 4; */
        if (message.concurrency !== 0)
            writer.tag(4, WireType.Varint).int32(message.concurrency);
        /* int32 timeout_seconds = 5; */
        if (message.timeoutSeconds !== 0)
            writer.tag(5, WireType.Varint).int32(message.timeoutSeconds);
        /* int64 max_input_pixels = 6; */
        if (message.maxInputPixels !== 0n)
            writer.tag(6, WireType.Varint).int64(message.maxInputPixels);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.PreviewSettings
 */
export const PreviewSettings = new PreviewSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PreviewJobSettings$Type extends MessageType<PreviewJobSettings> {
    constructor() {
        super("yatm.v1.PreviewJobSettings", [
            { no: 1, name: "generators", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PreviewGeneratorSettings }
        ]);
    }
    create(value?: PartialMessage<PreviewJobSettings>): PreviewJobSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.generators = [];
        if (value !== undefined)
            reflectionMergePartial<PreviewJobSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PreviewJobSettings): PreviewJobSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated yatm.v1.PreviewGeneratorSettings generators */ 1:
                    message.generators.push(PreviewGeneratorSettings.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PreviewJobSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated yatm.v1.PreviewGeneratorSettings generators = 1; */
        for (let i = 0; i < message.generators.length; i++)
            PreviewGeneratorSettings.internalBinaryWrite(message.generators[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.PreviewJobSettings
 */
export const PreviewJobSettings = new PreviewJobSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PreviewExtension$Type extends MessageType<PreviewExtension> {
    constructor() {
        super("yatm.v1.PreviewExtension", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<PreviewExtension>): PreviewExtension {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.enabled = false;
        if (value !== undefined)
            reflectionMergePartial<PreviewExtension>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PreviewExtension): PreviewExtension {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* bool enabled */ 2:
                    message.enabled = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PreviewExtension, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* bool enabled = 2; */
        if (message.enabled !== false)
            writer.tag(2, WireType.Varint).bool(message.enabled);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.PreviewExtension
 */
export const PreviewExtension = new PreviewExtension$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PreviewGeneratorSettings$Type extends MessageType<PreviewGeneratorSettings> {
    constructor() {
        super("yatm.v1.PreviewGeneratorSettings", [
            { no: 1, name: "enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "extensions", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PreviewExtension },
            { no: 3, name: "image", kind: "message", oneof: "options", T: () => ImagePreviewSettings },
            { no: 4, name: "video", kind: "message", oneof: "options", T: () => VideoPreviewSettings }
        ]);
    }
    create(value?: PartialMessage<PreviewGeneratorSettings>): PreviewGeneratorSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.enabled = false;
        message.extensions = [];
        message.options = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<PreviewGeneratorSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PreviewGeneratorSettings): PreviewGeneratorSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool enabled */ 1:
                    message.enabled = reader.bool();
                    break;
                case /* repeated yatm.v1.PreviewExtension extensions */ 2:
                    message.extensions.push(PreviewExtension.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* yatm.v1.ImagePreviewSettings image */ 3:
                    message.options = {
                        oneofKind: "image",
                        image: ImagePreviewSettings.internalBinaryRead(reader, reader.uint32(), options, (message.options as any).image)
                    };
                    break;
                case /* yatm.v1.VideoPreviewSettings video */ 4:
                    message.options = {
                        oneofKind: "video",
                        video: VideoPreviewSettings.internalBinaryRead(reader, reader.uint32(), options, (message.options as any).video)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PreviewGeneratorSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool enabled = 1; */
        if (message.enabled !== false)
            writer.tag(1, WireType.Varint).bool(message.enabled);
        /* repeated yatm.v1.PreviewExtension extensions = 2; */
        for (let i = 0; i < message.extensions.length; i++)
            PreviewExtension.internalBinaryWrite(message.extensions[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* yatm.v1.ImagePreviewSettings image = 3; */
        if (message.options.oneofKind === "image")
            ImagePreviewSettings.internalBinaryWrite(message.options.image, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* yatm.v1.VideoPreviewSettings video = 4; */
        if (message.options.oneofKind === "video")
            VideoPreviewSettings.internalBinaryWrite(message.options.video, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.PreviewGeneratorSettings
 */
export const PreviewGeneratorSettings = new PreviewGeneratorSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ImagePreviewSettings$Type extends MessageType<ImagePreviewSettings> {
    constructor() {
        super("yatm.v1.ImagePreviewSettings", [
            { no: 1, name: "max_width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "max_height", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "format", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "quality", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ImagePreviewSettings>): ImagePreviewSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.maxWidth = 0;
        message.maxHeight = 0;
        message.format = "";
        message.quality = 0;
        if (value !== undefined)
            reflectionMergePartial<ImagePreviewSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ImagePreviewSettings): ImagePreviewSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 max_width */ 1:
                    message.maxWidth = reader.int32();
                    break;
                case /* int32 max_height */ 2:
                    message.maxHeight = reader.int32();
                    break;
                case /* string format */ 3:
                    message.format = reader.string();
                    break;
                case /* int32 quality */ 4:
                    message.quality = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ImagePreviewSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 max_width = 1; */
        if (message.maxWidth !== 0)
            writer.tag(1, WireType.Varint).int32(message.maxWidth);
        /* int32 max_height = 2; */
        if (message.maxHeight !== 0)
            writer.tag(2, WireType.Varint).int32(message.maxHeight);
        /* string format = 3; */
        if (message.format !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.format);
        /* int32 quality = 4; */
        if (message.quality !== 0)
            writer.tag(4, WireType.Varint).int32(message.quality);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.ImagePreviewSettings
 */
export const ImagePreviewSettings = new ImagePreviewSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VideoPreviewSettings$Type extends MessageType<VideoPreviewSettings> {
    constructor() {
        super("yatm.v1.VideoPreviewSettings", [
            { no: 1, name: "poster_width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "poster_height", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "timeline_width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "timeline_height", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "timeline_interval_seconds", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "timeline_max_frames", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "format", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "quality", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<VideoPreviewSettings>): VideoPreviewSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.posterWidth = 0;
        message.posterHeight = 0;
        message.timelineWidth = 0;
        message.timelineHeight = 0;
        message.timelineIntervalSeconds = 0;
        message.timelineMaxFrames = 0;
        message.format = "";
        message.quality = 0;
        if (value !== undefined)
            reflectionMergePartial<VideoPreviewSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VideoPreviewSettings): VideoPreviewSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 poster_width */ 1:
                    message.posterWidth = reader.int32();
                    break;
                case /* int32 poster_height */ 2:
                    message.posterHeight = reader.int32();
                    break;
                case /* int32 timeline_width */ 3:
                    message.timelineWidth = reader.int32();
                    break;
                case /* int32 timeline_height */ 4:
                    message.timelineHeight = reader.int32();
                    break;
                case /* int32 timeline_interval_seconds */ 5:
                    message.timelineIntervalSeconds = reader.int32();
                    break;
                case /* int32 timeline_max_frames */ 6:
                    message.timelineMaxFrames = reader.int32();
                    break;
                case /* string format */ 7:
                    message.format = reader.string();
                    break;
                case /* int32 quality */ 8:
                    message.quality = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: VideoPreviewSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 poster_width = 1; */
        if (message.posterWidth !== 0)
            writer.tag(1, WireType.Varint).int32(message.posterWidth);
        /* int32 poster_height = 2; */
        if (message.posterHeight !== 0)
            writer.tag(2, WireType.Varint).int32(message.posterHeight);
        /* int32 timeline_width = 3; */
        if (message.timelineWidth !== 0)
            writer.tag(3, WireType.Varint).int32(message.timelineWidth);
        /* int32 timeline_height = 4; */
        if (message.timelineHeight !== 0)
            writer.tag(4, WireType.Varint).int32(message.timelineHeight);
        /* int32 timeline_interval_seconds = 5; */
        if (message.timelineIntervalSeconds !== 0)
            writer.tag(5, WireType.Varint).int32(message.timelineIntervalSeconds);
        /* int32 timeline_max_frames = 6; */
        if (message.timelineMaxFrames !== 0)
            writer.tag(6, WireType.Varint).int32(message.timelineMaxFrames);
        /* string format = 7; */
        if (message.format !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.format);
        /* int32 quality = 8; */
        if (message.quality !== 0)
            writer.tag(8, WireType.Varint).int32(message.quality);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.VideoPreviewSettings
 */
export const VideoPreviewSettings = new VideoPreviewSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SettingsValue$Type extends MessageType<SettingsValue> {
    constructor() {
        super("yatm.v1.SettingsValue", [
            { no: 1, name: "library", kind: "message", oneof: "value", T: () => LibrarySettings },
            { no: 2, name: "preview", kind: "message", oneof: "value", T: () => PreviewSettings },
            { no: 3, name: "job", kind: "message", oneof: "value", T: () => JobSettings }
        ]);
    }
    create(value?: PartialMessage<SettingsValue>): SettingsValue {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.value = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<SettingsValue>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SettingsValue): SettingsValue {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* yatm.v1.LibrarySettings library */ 1:
                    message.value = {
                        oneofKind: "library",
                        library: LibrarySettings.internalBinaryRead(reader, reader.uint32(), options, (message.value as any).library)
                    };
                    break;
                case /* yatm.v1.PreviewSettings preview */ 2:
                    message.value = {
                        oneofKind: "preview",
                        preview: PreviewSettings.internalBinaryRead(reader, reader.uint32(), options, (message.value as any).preview)
                    };
                    break;
                case /* yatm.v1.JobSettings job */ 3:
                    message.value = {
                        oneofKind: "job",
                        job: JobSettings.internalBinaryRead(reader, reader.uint32(), options, (message.value as any).job)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SettingsValue, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* yatm.v1.LibrarySettings library = 1; */
        if (message.value.oneofKind === "library")
            LibrarySettings.internalBinaryWrite(message.value.library, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* yatm.v1.PreviewSettings preview = 2; */
        if (message.value.oneofKind === "preview")
            PreviewSettings.internalBinaryWrite(message.value.preview, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* yatm.v1.JobSettings job = 3; */
        if (message.value.oneofKind === "job")
            JobSettings.internalBinaryWrite(message.value.job, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.SettingsValue
 */
export const SettingsValue = new SettingsValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSettingsRequest$Type extends MessageType<GetSettingsRequest> {
    constructor() {
        super("yatm.v1.GetSettingsRequest", [
            { no: 1, name: "group", kind: "enum", T: () => ["yatm.v1.SettingsGroup", SettingsGroup, "SETTINGS_GROUP_"] }
        ]);
    }
    create(value?: PartialMessage<GetSettingsRequest>): GetSettingsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.group = 0;
        if (value !== undefined)
            reflectionMergePartial<GetSettingsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSettingsRequest): GetSettingsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* yatm.v1.SettingsGroup group */ 1:
                    message.group = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSettingsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* yatm.v1.SettingsGroup group = 1; */
        if (message.group !== 0)
            writer.tag(1, WireType.Varint).int32(message.group);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.GetSettingsRequest
 */
export const GetSettingsRequest = new GetSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSettingsResponse$Type extends MessageType<GetSettingsResponse> {
    constructor() {
        super("yatm.v1.GetSettingsResponse", [
            { no: 1, name: "value", kind: "message", T: () => SettingsValue }
        ]);
    }
    create(value?: PartialMessage<GetSettingsResponse>): GetSettingsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetSettingsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSettingsResponse): GetSettingsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* yatm.v1.SettingsValue value */ 1:
                    message.value = SettingsValue.internalBinaryRead(reader, reader.uint32(), options, message.value);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSettingsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* yatm.v1.SettingsValue value = 1; */
        if (message.value)
            SettingsValue.internalBinaryWrite(message.value, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.GetSettingsResponse
 */
export const GetSettingsResponse = new GetSettingsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateSettingsRequest$Type extends MessageType<UpdateSettingsRequest> {
    constructor() {
        super("yatm.v1.UpdateSettingsRequest", [
            { no: 1, name: "value", kind: "message", T: () => SettingsValue }
        ]);
    }
    create(value?: PartialMessage<UpdateSettingsRequest>): UpdateSettingsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateSettingsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateSettingsRequest): UpdateSettingsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* yatm.v1.SettingsValue value */ 1:
                    message.value = SettingsValue.internalBinaryRead(reader, reader.uint32(), options, message.value);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateSettingsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* yatm.v1.SettingsValue value = 1; */
        if (message.value)
            SettingsValue.internalBinaryWrite(message.value, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.UpdateSettingsRequest
 */
export const UpdateSettingsRequest = new UpdateSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateSettingsResponse$Type extends MessageType<UpdateSettingsResponse> {
    constructor() {
        super("yatm.v1.UpdateSettingsResponse", [
            { no: 1, name: "value", kind: "message", T: () => SettingsValue }
        ]);
    }
    create(value?: PartialMessage<UpdateSettingsResponse>): UpdateSettingsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateSettingsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateSettingsResponse): UpdateSettingsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* yatm.v1.SettingsValue value */ 1:
                    message.value = SettingsValue.internalBinaryRead(reader, reader.uint32(), options, message.value);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateSettingsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* yatm.v1.SettingsValue value = 1; */
        if (message.value)
            SettingsValue.internalBinaryWrite(message.value, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.UpdateSettingsResponse
 */
export const UpdateSettingsResponse = new UpdateSettingsResponse$Type();
/**
 * @generated ServiceType for protobuf service yatm.v1.SettingsService
 */
export const SettingsService = new ServiceType("yatm.v1.SettingsService", [
    { name: "Get", options: {}, I: GetSettingsRequest, O: GetSettingsResponse },
    { name: "Update", options: {}, I: UpdateSettingsRequest, O: UpdateSettingsResponse }
]);
