// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "source.proto" (package "yatm.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message yatm.v1.SourceFile
 */
export interface SourceFile {
    /**
     * @generated from protobuf field: string path = 1
     */
    path: string;
    /**
     * @generated from protobuf field: string parent_path = 2
     */
    parentPath: string;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: int64 mode = 17
     */
    mode: bigint;
    /**
     * @generated from protobuf field: int64 mtime_ns = 18
     */
    mtimeNs: bigint;
    /**
     * @generated from protobuf field: int64 size_bytes = 19
     */
    sizeBytes: bigint;
}
// @generated message type with reflection information, may provide speed optimized methods
class SourceFile$Type extends MessageType<SourceFile> {
    constructor() {
        super("yatm.v1.SourceFile", [
            { no: 1, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "parent_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "mode", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 18, name: "mtime_ns", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 19, name: "size_bytes", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<SourceFile>): SourceFile {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.path = "";
        message.parentPath = "";
        message.name = "";
        message.mode = 0n;
        message.mtimeNs = 0n;
        message.sizeBytes = 0n;
        if (value !== undefined)
            reflectionMergePartial<SourceFile>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SourceFile): SourceFile {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string path */ 1:
                    message.path = reader.string();
                    break;
                case /* string parent_path */ 2:
                    message.parentPath = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* int64 mode */ 17:
                    message.mode = reader.int64().toBigInt();
                    break;
                case /* int64 mtime_ns */ 18:
                    message.mtimeNs = reader.int64().toBigInt();
                    break;
                case /* int64 size_bytes */ 19:
                    message.sizeBytes = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SourceFile, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string path = 1; */
        if (message.path !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.path);
        /* string parent_path = 2; */
        if (message.parentPath !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.parentPath);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* int64 mode = 17; */
        if (message.mode !== 0n)
            writer.tag(17, WireType.Varint).int64(message.mode);
        /* int64 mtime_ns = 18; */
        if (message.mtimeNs !== 0n)
            writer.tag(18, WireType.Varint).int64(message.mtimeNs);
        /* int64 size_bytes = 19; */
        if (message.sizeBytes !== 0n)
            writer.tag(19, WireType.Varint).int64(message.sizeBytes);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.SourceFile
 */
export const SourceFile = new SourceFile$Type();
