// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "storage.proto" (package "yatm.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message yatm.v1.LtfsExtent
 */
export interface LtfsExtent {
    /**
     * @generated from protobuf field: string partition = 1
     */
    partition: string;
    /**
     * @generated from protobuf field: uint64 start_block = 2
     */
    startBlock: bigint;
    /**
     * @generated from protobuf field: uint64 byte_offset = 3
     */
    byteOffset: bigint;
    /**
     * @generated from protobuf field: uint64 byte_count = 4
     */
    byteCount: bigint;
    /**
     * @generated from protobuf field: uint64 file_offset_bytes = 5
     */
    fileOffsetBytes: bigint;
}
/**
 * @generated from protobuf message yatm.v1.LtfsMetadata
 */
export interface LtfsMetadata {
    /**
     * @generated from protobuf field: repeated yatm.v1.LtfsExtent extents = 1
     */
    extents: LtfsExtent[];
}
/**
 * @generated from protobuf message yatm.v1.StorageMetadata
 */
export interface StorageMetadata {
    /**
     * @generated from protobuf oneof: backend
     */
    backend: {
        oneofKind: "ltfs";
        /**
         * @generated from protobuf field: yatm.v1.LtfsMetadata ltfs = 1
         */
        ltfs: LtfsMetadata;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message yatm.v1.StoragePosition
 */
export interface StoragePosition {
    /**
     * @generated from protobuf field: bytes order = 1
     */
    order: Uint8Array;
    /**
     * @generated from protobuf field: yatm.v1.StorageMetadata metadata = 2
     */
    metadata?: StorageMetadata;
}
// @generated message type with reflection information, may provide speed optimized methods
class LtfsExtent$Type extends MessageType<LtfsExtent> {
    constructor() {
        super("yatm.v1.LtfsExtent", [
            { no: 1, name: "partition", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "start_block", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "byte_offset", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "byte_count", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "file_offset_bytes", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<LtfsExtent>): LtfsExtent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.partition = "";
        message.startBlock = 0n;
        message.byteOffset = 0n;
        message.byteCount = 0n;
        message.fileOffsetBytes = 0n;
        if (value !== undefined)
            reflectionMergePartial<LtfsExtent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LtfsExtent): LtfsExtent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string partition */ 1:
                    message.partition = reader.string();
                    break;
                case /* uint64 start_block */ 2:
                    message.startBlock = reader.uint64().toBigInt();
                    break;
                case /* uint64 byte_offset */ 3:
                    message.byteOffset = reader.uint64().toBigInt();
                    break;
                case /* uint64 byte_count */ 4:
                    message.byteCount = reader.uint64().toBigInt();
                    break;
                case /* uint64 file_offset_bytes */ 5:
                    message.fileOffsetBytes = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LtfsExtent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string partition = 1; */
        if (message.partition !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.partition);
        /* uint64 start_block = 2; */
        if (message.startBlock !== 0n)
            writer.tag(2, WireType.Varint).uint64(message.startBlock);
        /* uint64 byte_offset = 3; */
        if (message.byteOffset !== 0n)
            writer.tag(3, WireType.Varint).uint64(message.byteOffset);
        /* uint64 byte_count = 4; */
        if (message.byteCount !== 0n)
            writer.tag(4, WireType.Varint).uint64(message.byteCount);
        /* uint64 file_offset_bytes = 5; */
        if (message.fileOffsetBytes !== 0n)
            writer.tag(5, WireType.Varint).uint64(message.fileOffsetBytes);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.LtfsExtent
 */
export const LtfsExtent = new LtfsExtent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LtfsMetadata$Type extends MessageType<LtfsMetadata> {
    constructor() {
        super("yatm.v1.LtfsMetadata", [
            { no: 1, name: "extents", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => LtfsExtent }
        ]);
    }
    create(value?: PartialMessage<LtfsMetadata>): LtfsMetadata {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.extents = [];
        if (value !== undefined)
            reflectionMergePartial<LtfsMetadata>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LtfsMetadata): LtfsMetadata {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated yatm.v1.LtfsExtent extents */ 1:
                    message.extents.push(LtfsExtent.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LtfsMetadata, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated yatm.v1.LtfsExtent extents = 1; */
        for (let i = 0; i < message.extents.length; i++)
            LtfsExtent.internalBinaryWrite(message.extents[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.LtfsMetadata
 */
export const LtfsMetadata = new LtfsMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StorageMetadata$Type extends MessageType<StorageMetadata> {
    constructor() {
        super("yatm.v1.StorageMetadata", [
            { no: 1, name: "ltfs", kind: "message", oneof: "backend", T: () => LtfsMetadata }
        ]);
    }
    create(value?: PartialMessage<StorageMetadata>): StorageMetadata {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.backend = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<StorageMetadata>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StorageMetadata): StorageMetadata {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* yatm.v1.LtfsMetadata ltfs */ 1:
                    message.backend = {
                        oneofKind: "ltfs",
                        ltfs: LtfsMetadata.internalBinaryRead(reader, reader.uint32(), options, (message.backend as any).ltfs)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StorageMetadata, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* yatm.v1.LtfsMetadata ltfs = 1; */
        if (message.backend.oneofKind === "ltfs")
            LtfsMetadata.internalBinaryWrite(message.backend.ltfs, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.StorageMetadata
 */
export const StorageMetadata = new StorageMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StoragePosition$Type extends MessageType<StoragePosition> {
    constructor() {
        super("yatm.v1.StoragePosition", [
            { no: 1, name: "order", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "metadata", kind: "message", T: () => StorageMetadata }
        ]);
    }
    create(value?: PartialMessage<StoragePosition>): StoragePosition {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.order = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<StoragePosition>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StoragePosition): StoragePosition {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes order */ 1:
                    message.order = reader.bytes();
                    break;
                case /* yatm.v1.StorageMetadata metadata */ 2:
                    message.metadata = StorageMetadata.internalBinaryRead(reader, reader.uint32(), options, message.metadata);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StoragePosition, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes order = 1; */
        if (message.order.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.order);
        /* yatm.v1.StorageMetadata metadata = 2; */
        if (message.metadata)
            StorageMetadata.internalBinaryWrite(message.metadata, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message yatm.v1.StoragePosition
 */
export const StoragePosition = new StoragePosition$Type();
