package demo

import _ "embed"

// The licensed excerpt and its native-worker derivatives are shipped together.
// Source, reproduction commands and checksums are in licenses/demo-video.LICENSE.
//
//go:embed assets/big-buck-bunny.mp4
var bundledVideo []byte

//go:embed assets/poster.png
var bundledVideoPoster []byte

//go:embed assets/timeline.png
var bundledVideoTimeline []byte

//go:embed assets/timeline.vtt
var bundledVideoTimelineMap []byte

const demoVideoName = "preview-video.mp4"

const demoVideoCredit = "Big Buck Bunny, five-minute silent excerpt (01:00–06:00), resized and transcoded. " +
	"(c) copyright 2008, Blender Foundation / www.bigbuckbunny.org. " +
	"CC BY 3.0: https://creativecommons.org/licenses/by/3.0/. " +
	"Poster and timeline generated by YATM's native Preview worker."
