#!/usr/bin/env bash
set -ex;

mkdir -p "${TAPE_DIR}"
exec > >(tee -a "${TAPE_DIR}/ltfs.log") 2>&1

mt -f "${DEVICE}" load
sleep 5

for i in {1..60}; do
    if stenc -f "${DEVICE}" -e on -k "${KEY_FILE}" -kd "${TAPE_BARCODE}" -a 1 --ckod; then
        sleep 3
        exit 0
    fi
    if (( i == 60 )); then
        exit 1
    fi
    sleep 5
done
