#!/usr/bin/env bash
set -ex;

mkdir -p "${TAPE_DIR}"
exec > >(tee -a "${TAPE_DIR}/ltfs.log") 2>&1

CURDIR=$(cd $(dirname $0); pwd);
SG_DEVICE=`${CURDIR}/get_device`

mkltfs -f -d ${SG_DEVICE} -s ${TAPE_BARCODE} -n ${TAPE_NAME}
sleep 3
