#!/usr/bin/env bash
set -ex;

SG_DEVICE=`sg_map | grep ${DEVICE} | awk '{print $1}'`
ltfs -o devname=${SG_DEVICE} -o noatime -o sync_type=unmount -o work_directory=/opt/ltfs -o capture_index -o min_pool_size=256 -o max_pool_size=1024 -o eject ${MOUNT_POINT}
sleep 3
